
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GlobalMember` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GlobalMember
 * 
 */
export type GlobalMemberModel = runtime.Types.Result.DefaultSelection<Prisma.$GlobalMemberPayload>

export type AggregateGlobalMember = {
  _count: GlobalMemberCountAggregateOutputType | null
  _min: GlobalMemberMinAggregateOutputType | null
  _max: GlobalMemberMaxAggregateOutputType | null
}

export type GlobalMemberMinAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  email: string | null
  phone: string | null
  gender: string | null
  dob: Date | null
  bloodGroup: string | null
  emergencyPhone: string | null
  emergencyName: string | null
  address: string | null
  avatar: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GlobalMemberMaxAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  email: string | null
  phone: string | null
  gender: string | null
  dob: Date | null
  bloodGroup: string | null
  emergencyPhone: string | null
  emergencyName: string | null
  address: string | null
  avatar: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GlobalMemberCountAggregateOutputType = {
  id: number
  firstName: number
  lastName: number
  email: number
  phone: number
  gender: number
  dob: number
  bloodGroup: number
  emergencyPhone: number
  emergencyName: number
  address: number
  avatar: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GlobalMemberMinAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  email?: true
  phone?: true
  gender?: true
  dob?: true
  bloodGroup?: true
  emergencyPhone?: true
  emergencyName?: true
  address?: true
  avatar?: true
  createdAt?: true
  updatedAt?: true
}

export type GlobalMemberMaxAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  email?: true
  phone?: true
  gender?: true
  dob?: true
  bloodGroup?: true
  emergencyPhone?: true
  emergencyName?: true
  address?: true
  avatar?: true
  createdAt?: true
  updatedAt?: true
}

export type GlobalMemberCountAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  email?: true
  phone?: true
  gender?: true
  dob?: true
  bloodGroup?: true
  emergencyPhone?: true
  emergencyName?: true
  address?: true
  avatar?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GlobalMemberAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalMember to aggregate.
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalMembers to fetch.
   */
  orderBy?: Prisma.GlobalMemberOrderByWithRelationInput | Prisma.GlobalMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GlobalMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GlobalMembers
  **/
  _count?: true | GlobalMemberCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GlobalMemberMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GlobalMemberMaxAggregateInputType
}

export type GetGlobalMemberAggregateType<T extends GlobalMemberAggregateArgs> = {
      [P in keyof T & keyof AggregateGlobalMember]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGlobalMember[P]>
    : Prisma.GetScalarType<T[P], AggregateGlobalMember[P]>
}




export type GlobalMemberGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GlobalMemberWhereInput
  orderBy?: Prisma.GlobalMemberOrderByWithAggregationInput | Prisma.GlobalMemberOrderByWithAggregationInput[]
  by: Prisma.GlobalMemberScalarFieldEnum[] | Prisma.GlobalMemberScalarFieldEnum
  having?: Prisma.GlobalMemberScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GlobalMemberCountAggregateInputType | true
  _min?: GlobalMemberMinAggregateInputType
  _max?: GlobalMemberMaxAggregateInputType
}

export type GlobalMemberGroupByOutputType = {
  id: string
  firstName: string
  lastName: string
  email: string | null
  phone: string
  gender: string | null
  dob: Date | null
  bloodGroup: string | null
  emergencyPhone: string | null
  emergencyName: string | null
  address: string | null
  avatar: string | null
  createdAt: Date
  updatedAt: Date
  _count: GlobalMemberCountAggregateOutputType | null
  _min: GlobalMemberMinAggregateOutputType | null
  _max: GlobalMemberMaxAggregateOutputType | null
}

export type GetGlobalMemberGroupByPayload<T extends GlobalMemberGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GlobalMemberGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GlobalMemberGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GlobalMemberGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GlobalMemberGroupByOutputType[P]>
      }
    >
  >



export type GlobalMemberWhereInput = {
  AND?: Prisma.GlobalMemberWhereInput | Prisma.GlobalMemberWhereInput[]
  OR?: Prisma.GlobalMemberWhereInput[]
  NOT?: Prisma.GlobalMemberWhereInput | Prisma.GlobalMemberWhereInput[]
  id?: Prisma.StringFilter<"GlobalMember"> | string
  firstName?: Prisma.StringFilter<"GlobalMember"> | string
  lastName?: Prisma.StringFilter<"GlobalMember"> | string
  email?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  phone?: Prisma.StringFilter<"GlobalMember"> | string
  gender?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  dob?: Prisma.DateTimeNullableFilter<"GlobalMember"> | Date | string | null
  bloodGroup?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  emergencyPhone?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  emergencyName?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  address?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  avatar?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GlobalMember"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GlobalMember"> | Date | string
}

export type GlobalMemberOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  dob?: Prisma.SortOrderInput | Prisma.SortOrder
  bloodGroup?: Prisma.SortOrderInput | Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  emergencyName?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalMemberWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  phone?: string
  AND?: Prisma.GlobalMemberWhereInput | Prisma.GlobalMemberWhereInput[]
  OR?: Prisma.GlobalMemberWhereInput[]
  NOT?: Prisma.GlobalMemberWhereInput | Prisma.GlobalMemberWhereInput[]
  firstName?: Prisma.StringFilter<"GlobalMember"> | string
  lastName?: Prisma.StringFilter<"GlobalMember"> | string
  gender?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  dob?: Prisma.DateTimeNullableFilter<"GlobalMember"> | Date | string | null
  bloodGroup?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  emergencyPhone?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  emergencyName?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  address?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  avatar?: Prisma.StringNullableFilter<"GlobalMember"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GlobalMember"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GlobalMember"> | Date | string
}, "id" | "email" | "phone">

export type GlobalMemberOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  dob?: Prisma.SortOrderInput | Prisma.SortOrder
  bloodGroup?: Prisma.SortOrderInput | Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  emergencyName?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GlobalMemberCountOrderByAggregateInput
  _max?: Prisma.GlobalMemberMaxOrderByAggregateInput
  _min?: Prisma.GlobalMemberMinOrderByAggregateInput
}

export type GlobalMemberScalarWhereWithAggregatesInput = {
  AND?: Prisma.GlobalMemberScalarWhereWithAggregatesInput | Prisma.GlobalMemberScalarWhereWithAggregatesInput[]
  OR?: Prisma.GlobalMemberScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GlobalMemberScalarWhereWithAggregatesInput | Prisma.GlobalMemberScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GlobalMember"> | string
  firstName?: Prisma.StringWithAggregatesFilter<"GlobalMember"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"GlobalMember"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  phone?: Prisma.StringWithAggregatesFilter<"GlobalMember"> | string
  gender?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  dob?: Prisma.DateTimeNullableWithAggregatesFilter<"GlobalMember"> | Date | string | null
  bloodGroup?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  emergencyPhone?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  emergencyName?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  avatar?: Prisma.StringNullableWithAggregatesFilter<"GlobalMember"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalMember"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GlobalMember"> | Date | string
}

export type GlobalMemberCreateInput = {
  id?: string
  firstName: string
  lastName: string
  email?: string | null
  phone: string
  gender?: string | null
  dob?: Date | string | null
  bloodGroup?: string | null
  emergencyPhone?: string | null
  emergencyName?: string | null
  address?: string | null
  avatar?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalMemberUncheckedCreateInput = {
  id?: string
  firstName: string
  lastName: string
  email?: string | null
  phone: string
  gender?: string | null
  dob?: Date | string | null
  bloodGroup?: string | null
  emergencyPhone?: string | null
  emergencyName?: string | null
  address?: string | null
  avatar?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalMemberUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dob?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bloodGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalMemberUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dob?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bloodGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalMemberCreateManyInput = {
  id?: string
  firstName: string
  lastName: string
  email?: string | null
  phone: string
  gender?: string | null
  dob?: Date | string | null
  bloodGroup?: string | null
  emergencyPhone?: string | null
  emergencyName?: string | null
  address?: string | null
  avatar?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GlobalMemberUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dob?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bloodGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalMemberUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dob?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bloodGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GlobalMemberCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dob?: Prisma.SortOrder
  bloodGroup?: Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrder
  emergencyName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalMemberMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dob?: Prisma.SortOrder
  bloodGroup?: Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrder
  emergencyName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GlobalMemberMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dob?: Prisma.SortOrder
  bloodGroup?: Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrder
  emergencyName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type GlobalMemberSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  phone?: boolean
  gender?: boolean
  dob?: boolean
  bloodGroup?: boolean
  emergencyPhone?: boolean
  emergencyName?: boolean
  address?: boolean
  avatar?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalMember"]>

export type GlobalMemberSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  phone?: boolean
  gender?: boolean
  dob?: boolean
  bloodGroup?: boolean
  emergencyPhone?: boolean
  emergencyName?: boolean
  address?: boolean
  avatar?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalMember"]>

export type GlobalMemberSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  phone?: boolean
  gender?: boolean
  dob?: boolean
  bloodGroup?: boolean
  emergencyPhone?: boolean
  emergencyName?: boolean
  address?: boolean
  avatar?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["globalMember"]>

export type GlobalMemberSelectScalar = {
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  email?: boolean
  phone?: boolean
  gender?: boolean
  dob?: boolean
  bloodGroup?: boolean
  emergencyPhone?: boolean
  emergencyName?: boolean
  address?: boolean
  avatar?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GlobalMemberOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "firstName" | "lastName" | "email" | "phone" | "gender" | "dob" | "bloodGroup" | "emergencyPhone" | "emergencyName" | "address" | "avatar" | "createdAt" | "updatedAt", ExtArgs["result"]["globalMember"]>

export type $GlobalMemberPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GlobalMember"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    firstName: string
    lastName: string
    email: string | null
    phone: string
    gender: string | null
    dob: Date | null
    bloodGroup: string | null
    emergencyPhone: string | null
    emergencyName: string | null
    address: string | null
    avatar: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["globalMember"]>
  composites: {}
}

export type GlobalMemberGetPayload<S extends boolean | null | undefined | GlobalMemberDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload, S>

export type GlobalMemberCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GlobalMemberFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GlobalMemberCountAggregateInputType | true
  }

export interface GlobalMemberDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GlobalMember'], meta: { name: 'GlobalMember' } }
  /**
   * Find zero or one GlobalMember that matches the filter.
   * @param {GlobalMemberFindUniqueArgs} args - Arguments to find a GlobalMember
   * @example
   * // Get one GlobalMember
   * const globalMember = await prisma.globalMember.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GlobalMemberFindUniqueArgs>(args: Prisma.SelectSubset<T, GlobalMemberFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GlobalMember that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GlobalMemberFindUniqueOrThrowArgs} args - Arguments to find a GlobalMember
   * @example
   * // Get one GlobalMember
   * const globalMember = await prisma.globalMember.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GlobalMemberFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GlobalMemberFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalMember that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberFindFirstArgs} args - Arguments to find a GlobalMember
   * @example
   * // Get one GlobalMember
   * const globalMember = await prisma.globalMember.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GlobalMemberFindFirstArgs>(args?: Prisma.SelectSubset<T, GlobalMemberFindFirstArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GlobalMember that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberFindFirstOrThrowArgs} args - Arguments to find a GlobalMember
   * @example
   * // Get one GlobalMember
   * const globalMember = await prisma.globalMember.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GlobalMemberFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GlobalMemberFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GlobalMembers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GlobalMembers
   * const globalMembers = await prisma.globalMember.findMany()
   * 
   * // Get first 10 GlobalMembers
   * const globalMembers = await prisma.globalMember.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const globalMemberWithIdOnly = await prisma.globalMember.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GlobalMemberFindManyArgs>(args?: Prisma.SelectSubset<T, GlobalMemberFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GlobalMember.
   * @param {GlobalMemberCreateArgs} args - Arguments to create a GlobalMember.
   * @example
   * // Create one GlobalMember
   * const GlobalMember = await prisma.globalMember.create({
   *   data: {
   *     // ... data to create a GlobalMember
   *   }
   * })
   * 
   */
  create<T extends GlobalMemberCreateArgs>(args: Prisma.SelectSubset<T, GlobalMemberCreateArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GlobalMembers.
   * @param {GlobalMemberCreateManyArgs} args - Arguments to create many GlobalMembers.
   * @example
   * // Create many GlobalMembers
   * const globalMember = await prisma.globalMember.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GlobalMemberCreateManyArgs>(args?: Prisma.SelectSubset<T, GlobalMemberCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GlobalMembers and returns the data saved in the database.
   * @param {GlobalMemberCreateManyAndReturnArgs} args - Arguments to create many GlobalMembers.
   * @example
   * // Create many GlobalMembers
   * const globalMember = await prisma.globalMember.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GlobalMembers and only return the `id`
   * const globalMemberWithIdOnly = await prisma.globalMember.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GlobalMemberCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GlobalMemberCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GlobalMember.
   * @param {GlobalMemberDeleteArgs} args - Arguments to delete one GlobalMember.
   * @example
   * // Delete one GlobalMember
   * const GlobalMember = await prisma.globalMember.delete({
   *   where: {
   *     // ... filter to delete one GlobalMember
   *   }
   * })
   * 
   */
  delete<T extends GlobalMemberDeleteArgs>(args: Prisma.SelectSubset<T, GlobalMemberDeleteArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GlobalMember.
   * @param {GlobalMemberUpdateArgs} args - Arguments to update one GlobalMember.
   * @example
   * // Update one GlobalMember
   * const globalMember = await prisma.globalMember.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GlobalMemberUpdateArgs>(args: Prisma.SelectSubset<T, GlobalMemberUpdateArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GlobalMembers.
   * @param {GlobalMemberDeleteManyArgs} args - Arguments to filter GlobalMembers to delete.
   * @example
   * // Delete a few GlobalMembers
   * const { count } = await prisma.globalMember.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GlobalMemberDeleteManyArgs>(args?: Prisma.SelectSubset<T, GlobalMemberDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GlobalMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GlobalMembers
   * const globalMember = await prisma.globalMember.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GlobalMemberUpdateManyArgs>(args: Prisma.SelectSubset<T, GlobalMemberUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GlobalMembers and returns the data updated in the database.
   * @param {GlobalMemberUpdateManyAndReturnArgs} args - Arguments to update many GlobalMembers.
   * @example
   * // Update many GlobalMembers
   * const globalMember = await prisma.globalMember.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GlobalMembers and only return the `id`
   * const globalMemberWithIdOnly = await prisma.globalMember.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GlobalMemberUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GlobalMemberUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GlobalMember.
   * @param {GlobalMemberUpsertArgs} args - Arguments to update or create a GlobalMember.
   * @example
   * // Update or create a GlobalMember
   * const globalMember = await prisma.globalMember.upsert({
   *   create: {
   *     // ... data to create a GlobalMember
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GlobalMember we want to update
   *   }
   * })
   */
  upsert<T extends GlobalMemberUpsertArgs>(args: Prisma.SelectSubset<T, GlobalMemberUpsertArgs<ExtArgs>>): Prisma.Prisma__GlobalMemberClient<runtime.Types.Result.GetResult<Prisma.$GlobalMemberPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GlobalMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberCountArgs} args - Arguments to filter GlobalMembers to count.
   * @example
   * // Count the number of GlobalMembers
   * const count = await prisma.globalMember.count({
   *   where: {
   *     // ... the filter for the GlobalMembers we want to count
   *   }
   * })
  **/
  count<T extends GlobalMemberCountArgs>(
    args?: Prisma.Subset<T, GlobalMemberCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GlobalMemberCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GlobalMember.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GlobalMemberAggregateArgs>(args: Prisma.Subset<T, GlobalMemberAggregateArgs>): Prisma.PrismaPromise<GetGlobalMemberAggregateType<T>>

  /**
   * Group by GlobalMember.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GlobalMemberGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GlobalMemberGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GlobalMemberGroupByArgs['orderBy'] }
      : { orderBy?: GlobalMemberGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GlobalMemberGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGlobalMemberGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GlobalMember model
 */
readonly fields: GlobalMemberFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GlobalMember.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GlobalMemberClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GlobalMember model
 */
export interface GlobalMemberFieldRefs {
  readonly id: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly firstName: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly lastName: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly email: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly phone: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly gender: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly dob: Prisma.FieldRef<"GlobalMember", 'DateTime'>
  readonly bloodGroup: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly emergencyPhone: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly emergencyName: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly address: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly avatar: Prisma.FieldRef<"GlobalMember", 'String'>
  readonly createdAt: Prisma.FieldRef<"GlobalMember", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GlobalMember", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GlobalMember findUnique
 */
export type GlobalMemberFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * Filter, which GlobalMember to fetch.
   */
  where: Prisma.GlobalMemberWhereUniqueInput
}

/**
 * GlobalMember findUniqueOrThrow
 */
export type GlobalMemberFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * Filter, which GlobalMember to fetch.
   */
  where: Prisma.GlobalMemberWhereUniqueInput
}

/**
 * GlobalMember findFirst
 */
export type GlobalMemberFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * Filter, which GlobalMember to fetch.
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalMembers to fetch.
   */
  orderBy?: Prisma.GlobalMemberOrderByWithRelationInput | Prisma.GlobalMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalMembers.
   */
  cursor?: Prisma.GlobalMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalMembers.
   */
  distinct?: Prisma.GlobalMemberScalarFieldEnum | Prisma.GlobalMemberScalarFieldEnum[]
}

/**
 * GlobalMember findFirstOrThrow
 */
export type GlobalMemberFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * Filter, which GlobalMember to fetch.
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalMembers to fetch.
   */
  orderBy?: Prisma.GlobalMemberOrderByWithRelationInput | Prisma.GlobalMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GlobalMembers.
   */
  cursor?: Prisma.GlobalMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalMembers.
   */
  distinct?: Prisma.GlobalMemberScalarFieldEnum | Prisma.GlobalMemberScalarFieldEnum[]
}

/**
 * GlobalMember findMany
 */
export type GlobalMemberFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * Filter, which GlobalMembers to fetch.
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GlobalMembers to fetch.
   */
  orderBy?: Prisma.GlobalMemberOrderByWithRelationInput | Prisma.GlobalMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GlobalMembers.
   */
  cursor?: Prisma.GlobalMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GlobalMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GlobalMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GlobalMembers.
   */
  distinct?: Prisma.GlobalMemberScalarFieldEnum | Prisma.GlobalMemberScalarFieldEnum[]
}

/**
 * GlobalMember create
 */
export type GlobalMemberCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * The data needed to create a GlobalMember.
   */
  data: Prisma.XOR<Prisma.GlobalMemberCreateInput, Prisma.GlobalMemberUncheckedCreateInput>
}

/**
 * GlobalMember createMany
 */
export type GlobalMemberCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GlobalMembers.
   */
  data: Prisma.GlobalMemberCreateManyInput | Prisma.GlobalMemberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GlobalMember createManyAndReturn
 */
export type GlobalMemberCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * The data used to create many GlobalMembers.
   */
  data: Prisma.GlobalMemberCreateManyInput | Prisma.GlobalMemberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GlobalMember update
 */
export type GlobalMemberUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * The data needed to update a GlobalMember.
   */
  data: Prisma.XOR<Prisma.GlobalMemberUpdateInput, Prisma.GlobalMemberUncheckedUpdateInput>
  /**
   * Choose, which GlobalMember to update.
   */
  where: Prisma.GlobalMemberWhereUniqueInput
}

/**
 * GlobalMember updateMany
 */
export type GlobalMemberUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GlobalMembers.
   */
  data: Prisma.XOR<Prisma.GlobalMemberUpdateManyMutationInput, Prisma.GlobalMemberUncheckedUpdateManyInput>
  /**
   * Filter which GlobalMembers to update
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * Limit how many GlobalMembers to update.
   */
  limit?: number
}

/**
 * GlobalMember updateManyAndReturn
 */
export type GlobalMemberUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * The data used to update GlobalMembers.
   */
  data: Prisma.XOR<Prisma.GlobalMemberUpdateManyMutationInput, Prisma.GlobalMemberUncheckedUpdateManyInput>
  /**
   * Filter which GlobalMembers to update
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * Limit how many GlobalMembers to update.
   */
  limit?: number
}

/**
 * GlobalMember upsert
 */
export type GlobalMemberUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * The filter to search for the GlobalMember to update in case it exists.
   */
  where: Prisma.GlobalMemberWhereUniqueInput
  /**
   * In case the GlobalMember found by the `where` argument doesn't exist, create a new GlobalMember with this data.
   */
  create: Prisma.XOR<Prisma.GlobalMemberCreateInput, Prisma.GlobalMemberUncheckedCreateInput>
  /**
   * In case the GlobalMember was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GlobalMemberUpdateInput, Prisma.GlobalMemberUncheckedUpdateInput>
}

/**
 * GlobalMember delete
 */
export type GlobalMemberDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
  /**
   * Filter which GlobalMember to delete.
   */
  where: Prisma.GlobalMemberWhereUniqueInput
}

/**
 * GlobalMember deleteMany
 */
export type GlobalMemberDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GlobalMembers to delete
   */
  where?: Prisma.GlobalMemberWhereInput
  /**
   * Limit how many GlobalMembers to delete.
   */
  limit?: number
}

/**
 * GlobalMember without action
 */
export type GlobalMemberDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GlobalMember
   */
  select?: Prisma.GlobalMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GlobalMember
   */
  omit?: Prisma.GlobalMemberOmit<ExtArgs> | null
}
