
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Gym` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Gym
 * 
 */
export type GymModel = runtime.Types.Result.DefaultSelection<Prisma.$GymPayload>

export type AggregateGym = {
  _count: GymCountAggregateOutputType | null
  _min: GymMinAggregateOutputType | null
  _max: GymMaxAggregateOutputType | null
}

export type GymMinAggregateOutputType = {
  id: string | null
  code: string | null
  schemaName: string | null
  name: string | null
  location: string | null
  address: string | null
  city: string | null
  state: string | null
  country: string | null
  pincode: string | null
  contactEmail: string | null
  contactPhone: string | null
  ownerName: string | null
  ownerPhone: string | null
  status: $Enums.GymStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GymMaxAggregateOutputType = {
  id: string | null
  code: string | null
  schemaName: string | null
  name: string | null
  location: string | null
  address: string | null
  city: string | null
  state: string | null
  country: string | null
  pincode: string | null
  contactEmail: string | null
  contactPhone: string | null
  ownerName: string | null
  ownerPhone: string | null
  status: $Enums.GymStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GymCountAggregateOutputType = {
  id: number
  code: number
  schemaName: number
  name: number
  location: number
  address: number
  city: number
  state: number
  country: number
  pincode: number
  contactEmail: number
  contactPhone: number
  ownerName: number
  ownerPhone: number
  status: number
  meta: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GymMinAggregateInputType = {
  id?: true
  code?: true
  schemaName?: true
  name?: true
  location?: true
  address?: true
  city?: true
  state?: true
  country?: true
  pincode?: true
  contactEmail?: true
  contactPhone?: true
  ownerName?: true
  ownerPhone?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type GymMaxAggregateInputType = {
  id?: true
  code?: true
  schemaName?: true
  name?: true
  location?: true
  address?: true
  city?: true
  state?: true
  country?: true
  pincode?: true
  contactEmail?: true
  contactPhone?: true
  ownerName?: true
  ownerPhone?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type GymCountAggregateInputType = {
  id?: true
  code?: true
  schemaName?: true
  name?: true
  location?: true
  address?: true
  city?: true
  state?: true
  country?: true
  pincode?: true
  contactEmail?: true
  contactPhone?: true
  ownerName?: true
  ownerPhone?: true
  status?: true
  meta?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GymAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Gym to aggregate.
   */
  where?: Prisma.GymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gyms to fetch.
   */
  orderBy?: Prisma.GymOrderByWithRelationInput | Prisma.GymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gyms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gyms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Gyms
  **/
  _count?: true | GymCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GymMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GymMaxAggregateInputType
}

export type GetGymAggregateType<T extends GymAggregateArgs> = {
      [P in keyof T & keyof AggregateGym]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGym[P]>
    : Prisma.GetScalarType<T[P], AggregateGym[P]>
}




export type GymGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GymWhereInput
  orderBy?: Prisma.GymOrderByWithAggregationInput | Prisma.GymOrderByWithAggregationInput[]
  by: Prisma.GymScalarFieldEnum[] | Prisma.GymScalarFieldEnum
  having?: Prisma.GymScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GymCountAggregateInputType | true
  _min?: GymMinAggregateInputType
  _max?: GymMaxAggregateInputType
}

export type GymGroupByOutputType = {
  id: string
  code: string
  schemaName: string
  name: string
  location: string
  address: string | null
  city: string | null
  state: string | null
  country: string | null
  pincode: string | null
  contactEmail: string | null
  contactPhone: string | null
  ownerName: string | null
  ownerPhone: string | null
  status: $Enums.GymStatus
  meta: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: GymCountAggregateOutputType | null
  _min: GymMinAggregateOutputType | null
  _max: GymMaxAggregateOutputType | null
}

export type GetGymGroupByPayload<T extends GymGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GymGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GymGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GymGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GymGroupByOutputType[P]>
      }
    >
  >



export type GymWhereInput = {
  AND?: Prisma.GymWhereInput | Prisma.GymWhereInput[]
  OR?: Prisma.GymWhereInput[]
  NOT?: Prisma.GymWhereInput | Prisma.GymWhereInput[]
  id?: Prisma.StringFilter<"Gym"> | string
  code?: Prisma.StringFilter<"Gym"> | string
  schemaName?: Prisma.StringFilter<"Gym"> | string
  name?: Prisma.StringFilter<"Gym"> | string
  location?: Prisma.StringFilter<"Gym"> | string
  address?: Prisma.StringNullableFilter<"Gym"> | string | null
  city?: Prisma.StringNullableFilter<"Gym"> | string | null
  state?: Prisma.StringNullableFilter<"Gym"> | string | null
  country?: Prisma.StringNullableFilter<"Gym"> | string | null
  pincode?: Prisma.StringNullableFilter<"Gym"> | string | null
  contactEmail?: Prisma.StringNullableFilter<"Gym"> | string | null
  contactPhone?: Prisma.StringNullableFilter<"Gym"> | string | null
  ownerName?: Prisma.StringNullableFilter<"Gym"> | string | null
  ownerPhone?: Prisma.StringNullableFilter<"Gym"> | string | null
  status?: Prisma.EnumGymStatusFilter<"Gym"> | $Enums.GymStatus
  meta?: Prisma.JsonNullableFilter<"Gym">
  createdAt?: Prisma.DateTimeFilter<"Gym"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Gym"> | Date | string
  users?: Prisma.GymUserListRelationFilter
  subscriptions?: Prisma.GymSubscriptionListRelationFilter
  featureFlags?: Prisma.GymFeatureListRelationFilter
  auditLogs?: Prisma.AuditLogListRelationFilter
}

export type GymOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  schemaName?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  state?: Prisma.SortOrderInput | Prisma.SortOrder
  country?: Prisma.SortOrderInput | Prisma.SortOrder
  pincode?: Prisma.SortOrderInput | Prisma.SortOrder
  contactEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerName?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  users?: Prisma.GymUserOrderByRelationAggregateInput
  subscriptions?: Prisma.GymSubscriptionOrderByRelationAggregateInput
  featureFlags?: Prisma.GymFeatureOrderByRelationAggregateInput
  auditLogs?: Prisma.AuditLogOrderByRelationAggregateInput
}

export type GymWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  schemaName?: string
  AND?: Prisma.GymWhereInput | Prisma.GymWhereInput[]
  OR?: Prisma.GymWhereInput[]
  NOT?: Prisma.GymWhereInput | Prisma.GymWhereInput[]
  name?: Prisma.StringFilter<"Gym"> | string
  location?: Prisma.StringFilter<"Gym"> | string
  address?: Prisma.StringNullableFilter<"Gym"> | string | null
  city?: Prisma.StringNullableFilter<"Gym"> | string | null
  state?: Prisma.StringNullableFilter<"Gym"> | string | null
  country?: Prisma.StringNullableFilter<"Gym"> | string | null
  pincode?: Prisma.StringNullableFilter<"Gym"> | string | null
  contactEmail?: Prisma.StringNullableFilter<"Gym"> | string | null
  contactPhone?: Prisma.StringNullableFilter<"Gym"> | string | null
  ownerName?: Prisma.StringNullableFilter<"Gym"> | string | null
  ownerPhone?: Prisma.StringNullableFilter<"Gym"> | string | null
  status?: Prisma.EnumGymStatusFilter<"Gym"> | $Enums.GymStatus
  meta?: Prisma.JsonNullableFilter<"Gym">
  createdAt?: Prisma.DateTimeFilter<"Gym"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Gym"> | Date | string
  users?: Prisma.GymUserListRelationFilter
  subscriptions?: Prisma.GymSubscriptionListRelationFilter
  featureFlags?: Prisma.GymFeatureListRelationFilter
  auditLogs?: Prisma.AuditLogListRelationFilter
}, "id" | "code" | "schemaName">

export type GymOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  schemaName?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  state?: Prisma.SortOrderInput | Prisma.SortOrder
  country?: Prisma.SortOrderInput | Prisma.SortOrder
  pincode?: Prisma.SortOrderInput | Prisma.SortOrder
  contactEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerName?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  meta?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GymCountOrderByAggregateInput
  _max?: Prisma.GymMaxOrderByAggregateInput
  _min?: Prisma.GymMinOrderByAggregateInput
}

export type GymScalarWhereWithAggregatesInput = {
  AND?: Prisma.GymScalarWhereWithAggregatesInput | Prisma.GymScalarWhereWithAggregatesInput[]
  OR?: Prisma.GymScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GymScalarWhereWithAggregatesInput | Prisma.GymScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Gym"> | string
  code?: Prisma.StringWithAggregatesFilter<"Gym"> | string
  schemaName?: Prisma.StringWithAggregatesFilter<"Gym"> | string
  name?: Prisma.StringWithAggregatesFilter<"Gym"> | string
  location?: Prisma.StringWithAggregatesFilter<"Gym"> | string
  address?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  city?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  state?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  country?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  pincode?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  contactEmail?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  contactPhone?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  ownerName?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  ownerPhone?: Prisma.StringNullableWithAggregatesFilter<"Gym"> | string | null
  status?: Prisma.EnumGymStatusWithAggregatesFilter<"Gym"> | $Enums.GymStatus
  meta?: Prisma.JsonNullableWithAggregatesFilter<"Gym">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Gym"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Gym"> | Date | string
}

export type GymCreateInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserCreateNestedManyWithoutGymInput
  subscriptions?: Prisma.GymSubscriptionCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogCreateNestedManyWithoutGymInput
}

export type GymUncheckedCreateInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserUncheckedCreateNestedManyWithoutGymInput
  subscriptions?: Prisma.GymSubscriptionUncheckedCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureUncheckedCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogUncheckedCreateNestedManyWithoutGymInput
}

export type GymUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUpdateManyWithoutGymNestedInput
  subscriptions?: Prisma.GymSubscriptionUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUpdateManyWithoutGymNestedInput
}

export type GymUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUncheckedUpdateManyWithoutGymNestedInput
  subscriptions?: Prisma.GymSubscriptionUncheckedUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUncheckedUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUncheckedUpdateManyWithoutGymNestedInput
}

export type GymCreateManyInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymScalarRelationFilter = {
  is?: Prisma.GymWhereInput
  isNot?: Prisma.GymWhereInput
}

export type GymCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  schemaName?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  state?: Prisma.SortOrder
  country?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  contactEmail?: Prisma.SortOrder
  contactPhone?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  ownerPhone?: Prisma.SortOrder
  status?: Prisma.SortOrder
  meta?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  schemaName?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  state?: Prisma.SortOrder
  country?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  contactEmail?: Prisma.SortOrder
  contactPhone?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  ownerPhone?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  schemaName?: Prisma.SortOrder
  name?: Prisma.SortOrder
  location?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  state?: Prisma.SortOrder
  country?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  contactEmail?: Prisma.SortOrder
  contactPhone?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  ownerPhone?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymNullableScalarRelationFilter = {
  is?: Prisma.GymWhereInput | null
  isNot?: Prisma.GymWhereInput | null
}

export type GymCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutUsersInput, Prisma.GymUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutUsersInput
  connect?: Prisma.GymWhereUniqueInput
}

export type GymUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutUsersInput, Prisma.GymUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutUsersInput
  upsert?: Prisma.GymUpsertWithoutUsersInput
  connect?: Prisma.GymWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GymUpdateToOneWithWhereWithoutUsersInput, Prisma.GymUpdateWithoutUsersInput>, Prisma.GymUncheckedUpdateWithoutUsersInput>
}

export type EnumGymStatusFieldUpdateOperationsInput = {
  set?: $Enums.GymStatus
}

export type GymCreateNestedOneWithoutSubscriptionsInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutSubscriptionsInput, Prisma.GymUncheckedCreateWithoutSubscriptionsInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutSubscriptionsInput
  connect?: Prisma.GymWhereUniqueInput
}

export type GymUpdateOneRequiredWithoutSubscriptionsNestedInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutSubscriptionsInput, Prisma.GymUncheckedCreateWithoutSubscriptionsInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutSubscriptionsInput
  upsert?: Prisma.GymUpsertWithoutSubscriptionsInput
  connect?: Prisma.GymWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GymUpdateToOneWithWhereWithoutSubscriptionsInput, Prisma.GymUpdateWithoutSubscriptionsInput>, Prisma.GymUncheckedUpdateWithoutSubscriptionsInput>
}

export type GymCreateNestedOneWithoutFeatureFlagsInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutFeatureFlagsInput, Prisma.GymUncheckedCreateWithoutFeatureFlagsInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutFeatureFlagsInput
  connect?: Prisma.GymWhereUniqueInput
}

export type GymUpdateOneRequiredWithoutFeatureFlagsNestedInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutFeatureFlagsInput, Prisma.GymUncheckedCreateWithoutFeatureFlagsInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutFeatureFlagsInput
  upsert?: Prisma.GymUpsertWithoutFeatureFlagsInput
  connect?: Prisma.GymWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GymUpdateToOneWithWhereWithoutFeatureFlagsInput, Prisma.GymUpdateWithoutFeatureFlagsInput>, Prisma.GymUncheckedUpdateWithoutFeatureFlagsInput>
}

export type GymCreateNestedOneWithoutAuditLogsInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutAuditLogsInput, Prisma.GymUncheckedCreateWithoutAuditLogsInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutAuditLogsInput
  connect?: Prisma.GymWhereUniqueInput
}

export type GymUpdateOneWithoutAuditLogsNestedInput = {
  create?: Prisma.XOR<Prisma.GymCreateWithoutAuditLogsInput, Prisma.GymUncheckedCreateWithoutAuditLogsInput>
  connectOrCreate?: Prisma.GymCreateOrConnectWithoutAuditLogsInput
  upsert?: Prisma.GymUpsertWithoutAuditLogsInput
  disconnect?: Prisma.GymWhereInput | boolean
  delete?: Prisma.GymWhereInput | boolean
  connect?: Prisma.GymWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GymUpdateToOneWithWhereWithoutAuditLogsInput, Prisma.GymUpdateWithoutAuditLogsInput>, Prisma.GymUncheckedUpdateWithoutAuditLogsInput>
}

export type GymCreateWithoutUsersInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  subscriptions?: Prisma.GymSubscriptionCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogCreateNestedManyWithoutGymInput
}

export type GymUncheckedCreateWithoutUsersInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  subscriptions?: Prisma.GymSubscriptionUncheckedCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureUncheckedCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogUncheckedCreateNestedManyWithoutGymInput
}

export type GymCreateOrConnectWithoutUsersInput = {
  where: Prisma.GymWhereUniqueInput
  create: Prisma.XOR<Prisma.GymCreateWithoutUsersInput, Prisma.GymUncheckedCreateWithoutUsersInput>
}

export type GymUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.GymUpdateWithoutUsersInput, Prisma.GymUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.GymCreateWithoutUsersInput, Prisma.GymUncheckedCreateWithoutUsersInput>
  where?: Prisma.GymWhereInput
}

export type GymUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.GymWhereInput
  data: Prisma.XOR<Prisma.GymUpdateWithoutUsersInput, Prisma.GymUncheckedUpdateWithoutUsersInput>
}

export type GymUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscriptions?: Prisma.GymSubscriptionUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUpdateManyWithoutGymNestedInput
}

export type GymUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subscriptions?: Prisma.GymSubscriptionUncheckedUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUncheckedUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUncheckedUpdateManyWithoutGymNestedInput
}

export type GymCreateWithoutSubscriptionsInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogCreateNestedManyWithoutGymInput
}

export type GymUncheckedCreateWithoutSubscriptionsInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserUncheckedCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureUncheckedCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogUncheckedCreateNestedManyWithoutGymInput
}

export type GymCreateOrConnectWithoutSubscriptionsInput = {
  where: Prisma.GymWhereUniqueInput
  create: Prisma.XOR<Prisma.GymCreateWithoutSubscriptionsInput, Prisma.GymUncheckedCreateWithoutSubscriptionsInput>
}

export type GymUpsertWithoutSubscriptionsInput = {
  update: Prisma.XOR<Prisma.GymUpdateWithoutSubscriptionsInput, Prisma.GymUncheckedUpdateWithoutSubscriptionsInput>
  create: Prisma.XOR<Prisma.GymCreateWithoutSubscriptionsInput, Prisma.GymUncheckedCreateWithoutSubscriptionsInput>
  where?: Prisma.GymWhereInput
}

export type GymUpdateToOneWithWhereWithoutSubscriptionsInput = {
  where?: Prisma.GymWhereInput
  data: Prisma.XOR<Prisma.GymUpdateWithoutSubscriptionsInput, Prisma.GymUncheckedUpdateWithoutSubscriptionsInput>
}

export type GymUpdateWithoutSubscriptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUpdateManyWithoutGymNestedInput
}

export type GymUncheckedUpdateWithoutSubscriptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUncheckedUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUncheckedUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUncheckedUpdateManyWithoutGymNestedInput
}

export type GymCreateWithoutFeatureFlagsInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserCreateNestedManyWithoutGymInput
  subscriptions?: Prisma.GymSubscriptionCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogCreateNestedManyWithoutGymInput
}

export type GymUncheckedCreateWithoutFeatureFlagsInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserUncheckedCreateNestedManyWithoutGymInput
  subscriptions?: Prisma.GymSubscriptionUncheckedCreateNestedManyWithoutGymInput
  auditLogs?: Prisma.AuditLogUncheckedCreateNestedManyWithoutGymInput
}

export type GymCreateOrConnectWithoutFeatureFlagsInput = {
  where: Prisma.GymWhereUniqueInput
  create: Prisma.XOR<Prisma.GymCreateWithoutFeatureFlagsInput, Prisma.GymUncheckedCreateWithoutFeatureFlagsInput>
}

export type GymUpsertWithoutFeatureFlagsInput = {
  update: Prisma.XOR<Prisma.GymUpdateWithoutFeatureFlagsInput, Prisma.GymUncheckedUpdateWithoutFeatureFlagsInput>
  create: Prisma.XOR<Prisma.GymCreateWithoutFeatureFlagsInput, Prisma.GymUncheckedCreateWithoutFeatureFlagsInput>
  where?: Prisma.GymWhereInput
}

export type GymUpdateToOneWithWhereWithoutFeatureFlagsInput = {
  where?: Prisma.GymWhereInput
  data: Prisma.XOR<Prisma.GymUpdateWithoutFeatureFlagsInput, Prisma.GymUncheckedUpdateWithoutFeatureFlagsInput>
}

export type GymUpdateWithoutFeatureFlagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUpdateManyWithoutGymNestedInput
  subscriptions?: Prisma.GymSubscriptionUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUpdateManyWithoutGymNestedInput
}

export type GymUncheckedUpdateWithoutFeatureFlagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUncheckedUpdateManyWithoutGymNestedInput
  subscriptions?: Prisma.GymSubscriptionUncheckedUpdateManyWithoutGymNestedInput
  auditLogs?: Prisma.AuditLogUncheckedUpdateManyWithoutGymNestedInput
}

export type GymCreateWithoutAuditLogsInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserCreateNestedManyWithoutGymInput
  subscriptions?: Prisma.GymSubscriptionCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureCreateNestedManyWithoutGymInput
}

export type GymUncheckedCreateWithoutAuditLogsInput = {
  id?: string
  code: string
  schemaName: string
  name: string
  location: string
  address?: string | null
  city?: string | null
  state?: string | null
  country?: string | null
  pincode?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  ownerName?: string | null
  ownerPhone?: string | null
  status?: $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.GymUserUncheckedCreateNestedManyWithoutGymInput
  subscriptions?: Prisma.GymSubscriptionUncheckedCreateNestedManyWithoutGymInput
  featureFlags?: Prisma.GymFeatureUncheckedCreateNestedManyWithoutGymInput
}

export type GymCreateOrConnectWithoutAuditLogsInput = {
  where: Prisma.GymWhereUniqueInput
  create: Prisma.XOR<Prisma.GymCreateWithoutAuditLogsInput, Prisma.GymUncheckedCreateWithoutAuditLogsInput>
}

export type GymUpsertWithoutAuditLogsInput = {
  update: Prisma.XOR<Prisma.GymUpdateWithoutAuditLogsInput, Prisma.GymUncheckedUpdateWithoutAuditLogsInput>
  create: Prisma.XOR<Prisma.GymCreateWithoutAuditLogsInput, Prisma.GymUncheckedCreateWithoutAuditLogsInput>
  where?: Prisma.GymWhereInput
}

export type GymUpdateToOneWithWhereWithoutAuditLogsInput = {
  where?: Prisma.GymWhereInput
  data: Prisma.XOR<Prisma.GymUpdateWithoutAuditLogsInput, Prisma.GymUncheckedUpdateWithoutAuditLogsInput>
}

export type GymUpdateWithoutAuditLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUpdateManyWithoutGymNestedInput
  subscriptions?: Prisma.GymSubscriptionUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUpdateManyWithoutGymNestedInput
}

export type GymUncheckedUpdateWithoutAuditLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  schemaName?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pincode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumGymStatusFieldUpdateOperationsInput | $Enums.GymStatus
  meta?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.GymUserUncheckedUpdateManyWithoutGymNestedInput
  subscriptions?: Prisma.GymSubscriptionUncheckedUpdateManyWithoutGymNestedInput
  featureFlags?: Prisma.GymFeatureUncheckedUpdateManyWithoutGymNestedInput
}


/**
 * Count Type GymCountOutputType
 */

export type GymCountOutputType = {
  users: number
  subscriptions: number
  featureFlags: number
  auditLogs: number
}

export type GymCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | GymCountOutputTypeCountUsersArgs
  subscriptions?: boolean | GymCountOutputTypeCountSubscriptionsArgs
  featureFlags?: boolean | GymCountOutputTypeCountFeatureFlagsArgs
  auditLogs?: boolean | GymCountOutputTypeCountAuditLogsArgs
}

/**
 * GymCountOutputType without action
 */
export type GymCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymCountOutputType
   */
  select?: Prisma.GymCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GymCountOutputType without action
 */
export type GymCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GymUserWhereInput
}

/**
 * GymCountOutputType without action
 */
export type GymCountOutputTypeCountSubscriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GymSubscriptionWhereInput
}

/**
 * GymCountOutputType without action
 */
export type GymCountOutputTypeCountFeatureFlagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GymFeatureWhereInput
}

/**
 * GymCountOutputType without action
 */
export type GymCountOutputTypeCountAuditLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuditLogWhereInput
}


export type GymSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  schemaName?: boolean
  name?: boolean
  location?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  country?: boolean
  pincode?: boolean
  contactEmail?: boolean
  contactPhone?: boolean
  ownerName?: boolean
  ownerPhone?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  users?: boolean | Prisma.Gym$usersArgs<ExtArgs>
  subscriptions?: boolean | Prisma.Gym$subscriptionsArgs<ExtArgs>
  featureFlags?: boolean | Prisma.Gym$featureFlagsArgs<ExtArgs>
  auditLogs?: boolean | Prisma.Gym$auditLogsArgs<ExtArgs>
  _count?: boolean | Prisma.GymCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gym"]>

export type GymSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  schemaName?: boolean
  name?: boolean
  location?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  country?: boolean
  pincode?: boolean
  contactEmail?: boolean
  contactPhone?: boolean
  ownerName?: boolean
  ownerPhone?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["gym"]>

export type GymSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  schemaName?: boolean
  name?: boolean
  location?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  country?: boolean
  pincode?: boolean
  contactEmail?: boolean
  contactPhone?: boolean
  ownerName?: boolean
  ownerPhone?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["gym"]>

export type GymSelectScalar = {
  id?: boolean
  code?: boolean
  schemaName?: boolean
  name?: boolean
  location?: boolean
  address?: boolean
  city?: boolean
  state?: boolean
  country?: boolean
  pincode?: boolean
  contactEmail?: boolean
  contactPhone?: boolean
  ownerName?: boolean
  ownerPhone?: boolean
  status?: boolean
  meta?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GymOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "schemaName" | "name" | "location" | "address" | "city" | "state" | "country" | "pincode" | "contactEmail" | "contactPhone" | "ownerName" | "ownerPhone" | "status" | "meta" | "createdAt" | "updatedAt", ExtArgs["result"]["gym"]>
export type GymInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.Gym$usersArgs<ExtArgs>
  subscriptions?: boolean | Prisma.Gym$subscriptionsArgs<ExtArgs>
  featureFlags?: boolean | Prisma.Gym$featureFlagsArgs<ExtArgs>
  auditLogs?: boolean | Prisma.Gym$auditLogsArgs<ExtArgs>
  _count?: boolean | Prisma.GymCountOutputTypeDefaultArgs<ExtArgs>
}
export type GymIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type GymIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $GymPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Gym"
  objects: {
    users: Prisma.$GymUserPayload<ExtArgs>[]
    subscriptions: Prisma.$GymSubscriptionPayload<ExtArgs>[]
    featureFlags: Prisma.$GymFeaturePayload<ExtArgs>[]
    auditLogs: Prisma.$AuditLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    schemaName: string
    name: string
    location: string
    address: string | null
    city: string | null
    state: string | null
    country: string | null
    pincode: string | null
    contactEmail: string | null
    contactPhone: string | null
    ownerName: string | null
    ownerPhone: string | null
    status: $Enums.GymStatus
    meta: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["gym"]>
  composites: {}
}

export type GymGetPayload<S extends boolean | null | undefined | GymDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GymPayload, S>

export type GymCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GymFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GymCountAggregateInputType | true
  }

export interface GymDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Gym'], meta: { name: 'Gym' } }
  /**
   * Find zero or one Gym that matches the filter.
   * @param {GymFindUniqueArgs} args - Arguments to find a Gym
   * @example
   * // Get one Gym
   * const gym = await prisma.gym.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GymFindUniqueArgs>(args: Prisma.SelectSubset<T, GymFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Gym that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GymFindUniqueOrThrowArgs} args - Arguments to find a Gym
   * @example
   * // Get one Gym
   * const gym = await prisma.gym.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GymFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GymFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Gym that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymFindFirstArgs} args - Arguments to find a Gym
   * @example
   * // Get one Gym
   * const gym = await prisma.gym.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GymFindFirstArgs>(args?: Prisma.SelectSubset<T, GymFindFirstArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Gym that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymFindFirstOrThrowArgs} args - Arguments to find a Gym
   * @example
   * // Get one Gym
   * const gym = await prisma.gym.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GymFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GymFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Gyms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Gyms
   * const gyms = await prisma.gym.findMany()
   * 
   * // Get first 10 Gyms
   * const gyms = await prisma.gym.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gymWithIdOnly = await prisma.gym.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GymFindManyArgs>(args?: Prisma.SelectSubset<T, GymFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Gym.
   * @param {GymCreateArgs} args - Arguments to create a Gym.
   * @example
   * // Create one Gym
   * const Gym = await prisma.gym.create({
   *   data: {
   *     // ... data to create a Gym
   *   }
   * })
   * 
   */
  create<T extends GymCreateArgs>(args: Prisma.SelectSubset<T, GymCreateArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Gyms.
   * @param {GymCreateManyArgs} args - Arguments to create many Gyms.
   * @example
   * // Create many Gyms
   * const gym = await prisma.gym.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GymCreateManyArgs>(args?: Prisma.SelectSubset<T, GymCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Gyms and returns the data saved in the database.
   * @param {GymCreateManyAndReturnArgs} args - Arguments to create many Gyms.
   * @example
   * // Create many Gyms
   * const gym = await prisma.gym.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Gyms and only return the `id`
   * const gymWithIdOnly = await prisma.gym.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GymCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GymCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Gym.
   * @param {GymDeleteArgs} args - Arguments to delete one Gym.
   * @example
   * // Delete one Gym
   * const Gym = await prisma.gym.delete({
   *   where: {
   *     // ... filter to delete one Gym
   *   }
   * })
   * 
   */
  delete<T extends GymDeleteArgs>(args: Prisma.SelectSubset<T, GymDeleteArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Gym.
   * @param {GymUpdateArgs} args - Arguments to update one Gym.
   * @example
   * // Update one Gym
   * const gym = await prisma.gym.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GymUpdateArgs>(args: Prisma.SelectSubset<T, GymUpdateArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Gyms.
   * @param {GymDeleteManyArgs} args - Arguments to filter Gyms to delete.
   * @example
   * // Delete a few Gyms
   * const { count } = await prisma.gym.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GymDeleteManyArgs>(args?: Prisma.SelectSubset<T, GymDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Gyms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Gyms
   * const gym = await prisma.gym.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GymUpdateManyArgs>(args: Prisma.SelectSubset<T, GymUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Gyms and returns the data updated in the database.
   * @param {GymUpdateManyAndReturnArgs} args - Arguments to update many Gyms.
   * @example
   * // Update many Gyms
   * const gym = await prisma.gym.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Gyms and only return the `id`
   * const gymWithIdOnly = await prisma.gym.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GymUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GymUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Gym.
   * @param {GymUpsertArgs} args - Arguments to update or create a Gym.
   * @example
   * // Update or create a Gym
   * const gym = await prisma.gym.upsert({
   *   create: {
   *     // ... data to create a Gym
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Gym we want to update
   *   }
   * })
   */
  upsert<T extends GymUpsertArgs>(args: Prisma.SelectSubset<T, GymUpsertArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Gyms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymCountArgs} args - Arguments to filter Gyms to count.
   * @example
   * // Count the number of Gyms
   * const count = await prisma.gym.count({
   *   where: {
   *     // ... the filter for the Gyms we want to count
   *   }
   * })
  **/
  count<T extends GymCountArgs>(
    args?: Prisma.Subset<T, GymCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GymCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Gym.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GymAggregateArgs>(args: Prisma.Subset<T, GymAggregateArgs>): Prisma.PrismaPromise<GetGymAggregateType<T>>

  /**
   * Group by Gym.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GymGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GymGroupByArgs['orderBy'] }
      : { orderBy?: GymGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GymGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGymGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Gym model
 */
readonly fields: GymFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Gym.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GymClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.Gym$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Gym$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  subscriptions<T extends Prisma.Gym$subscriptionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Gym$subscriptionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  featureFlags<T extends Prisma.Gym$featureFlagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Gym$featureFlagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymFeaturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  auditLogs<T extends Prisma.Gym$auditLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Gym$auditLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuditLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Gym model
 */
export interface GymFieldRefs {
  readonly id: Prisma.FieldRef<"Gym", 'String'>
  readonly code: Prisma.FieldRef<"Gym", 'String'>
  readonly schemaName: Prisma.FieldRef<"Gym", 'String'>
  readonly name: Prisma.FieldRef<"Gym", 'String'>
  readonly location: Prisma.FieldRef<"Gym", 'String'>
  readonly address: Prisma.FieldRef<"Gym", 'String'>
  readonly city: Prisma.FieldRef<"Gym", 'String'>
  readonly state: Prisma.FieldRef<"Gym", 'String'>
  readonly country: Prisma.FieldRef<"Gym", 'String'>
  readonly pincode: Prisma.FieldRef<"Gym", 'String'>
  readonly contactEmail: Prisma.FieldRef<"Gym", 'String'>
  readonly contactPhone: Prisma.FieldRef<"Gym", 'String'>
  readonly ownerName: Prisma.FieldRef<"Gym", 'String'>
  readonly ownerPhone: Prisma.FieldRef<"Gym", 'String'>
  readonly status: Prisma.FieldRef<"Gym", 'GymStatus'>
  readonly meta: Prisma.FieldRef<"Gym", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Gym", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Gym", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Gym findUnique
 */
export type GymFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * Filter, which Gym to fetch.
   */
  where: Prisma.GymWhereUniqueInput
}

/**
 * Gym findUniqueOrThrow
 */
export type GymFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * Filter, which Gym to fetch.
   */
  where: Prisma.GymWhereUniqueInput
}

/**
 * Gym findFirst
 */
export type GymFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * Filter, which Gym to fetch.
   */
  where?: Prisma.GymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gyms to fetch.
   */
  orderBy?: Prisma.GymOrderByWithRelationInput | Prisma.GymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Gyms.
   */
  cursor?: Prisma.GymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gyms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gyms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Gyms.
   */
  distinct?: Prisma.GymScalarFieldEnum | Prisma.GymScalarFieldEnum[]
}

/**
 * Gym findFirstOrThrow
 */
export type GymFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * Filter, which Gym to fetch.
   */
  where?: Prisma.GymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gyms to fetch.
   */
  orderBy?: Prisma.GymOrderByWithRelationInput | Prisma.GymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Gyms.
   */
  cursor?: Prisma.GymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gyms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gyms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Gyms.
   */
  distinct?: Prisma.GymScalarFieldEnum | Prisma.GymScalarFieldEnum[]
}

/**
 * Gym findMany
 */
export type GymFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * Filter, which Gyms to fetch.
   */
  where?: Prisma.GymWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Gyms to fetch.
   */
  orderBy?: Prisma.GymOrderByWithRelationInput | Prisma.GymOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Gyms.
   */
  cursor?: Prisma.GymWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Gyms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Gyms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Gyms.
   */
  distinct?: Prisma.GymScalarFieldEnum | Prisma.GymScalarFieldEnum[]
}

/**
 * Gym create
 */
export type GymCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * The data needed to create a Gym.
   */
  data: Prisma.XOR<Prisma.GymCreateInput, Prisma.GymUncheckedCreateInput>
}

/**
 * Gym createMany
 */
export type GymCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Gyms.
   */
  data: Prisma.GymCreateManyInput | Prisma.GymCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Gym createManyAndReturn
 */
export type GymCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * The data used to create many Gyms.
   */
  data: Prisma.GymCreateManyInput | Prisma.GymCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Gym update
 */
export type GymUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * The data needed to update a Gym.
   */
  data: Prisma.XOR<Prisma.GymUpdateInput, Prisma.GymUncheckedUpdateInput>
  /**
   * Choose, which Gym to update.
   */
  where: Prisma.GymWhereUniqueInput
}

/**
 * Gym updateMany
 */
export type GymUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Gyms.
   */
  data: Prisma.XOR<Prisma.GymUpdateManyMutationInput, Prisma.GymUncheckedUpdateManyInput>
  /**
   * Filter which Gyms to update
   */
  where?: Prisma.GymWhereInput
  /**
   * Limit how many Gyms to update.
   */
  limit?: number
}

/**
 * Gym updateManyAndReturn
 */
export type GymUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * The data used to update Gyms.
   */
  data: Prisma.XOR<Prisma.GymUpdateManyMutationInput, Prisma.GymUncheckedUpdateManyInput>
  /**
   * Filter which Gyms to update
   */
  where?: Prisma.GymWhereInput
  /**
   * Limit how many Gyms to update.
   */
  limit?: number
}

/**
 * Gym upsert
 */
export type GymUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * The filter to search for the Gym to update in case it exists.
   */
  where: Prisma.GymWhereUniqueInput
  /**
   * In case the Gym found by the `where` argument doesn't exist, create a new Gym with this data.
   */
  create: Prisma.XOR<Prisma.GymCreateInput, Prisma.GymUncheckedCreateInput>
  /**
   * In case the Gym was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GymUpdateInput, Prisma.GymUncheckedUpdateInput>
}

/**
 * Gym delete
 */
export type GymDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
  /**
   * Filter which Gym to delete.
   */
  where: Prisma.GymWhereUniqueInput
}

/**
 * Gym deleteMany
 */
export type GymDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Gyms to delete
   */
  where?: Prisma.GymWhereInput
  /**
   * Limit how many Gyms to delete.
   */
  limit?: number
}

/**
 * Gym.users
 */
export type Gym$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  where?: Prisma.GymUserWhereInput
  orderBy?: Prisma.GymUserOrderByWithRelationInput | Prisma.GymUserOrderByWithRelationInput[]
  cursor?: Prisma.GymUserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GymUserScalarFieldEnum | Prisma.GymUserScalarFieldEnum[]
}

/**
 * Gym.subscriptions
 */
export type Gym$subscriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  where?: Prisma.GymSubscriptionWhereInput
  orderBy?: Prisma.GymSubscriptionOrderByWithRelationInput | Prisma.GymSubscriptionOrderByWithRelationInput[]
  cursor?: Prisma.GymSubscriptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GymSubscriptionScalarFieldEnum | Prisma.GymSubscriptionScalarFieldEnum[]
}

/**
 * Gym.featureFlags
 */
export type Gym$featureFlagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymFeature
   */
  select?: Prisma.GymFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymFeature
   */
  omit?: Prisma.GymFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymFeatureInclude<ExtArgs> | null
  where?: Prisma.GymFeatureWhereInput
  orderBy?: Prisma.GymFeatureOrderByWithRelationInput | Prisma.GymFeatureOrderByWithRelationInput[]
  cursor?: Prisma.GymFeatureWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GymFeatureScalarFieldEnum | Prisma.GymFeatureScalarFieldEnum[]
}

/**
 * Gym.auditLogs
 */
export type Gym$auditLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuditLog
   */
  select?: Prisma.AuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuditLog
   */
  omit?: Prisma.AuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditLogInclude<ExtArgs> | null
  where?: Prisma.AuditLogWhereInput
  orderBy?: Prisma.AuditLogOrderByWithRelationInput | Prisma.AuditLogOrderByWithRelationInput[]
  cursor?: Prisma.AuditLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuditLogScalarFieldEnum | Prisma.AuditLogScalarFieldEnum[]
}

/**
 * Gym without action
 */
export type GymDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gym
   */
  select?: Prisma.GymSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gym
   */
  omit?: Prisma.GymOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymInclude<ExtArgs> | null
}
