
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GymSubscription` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GymSubscription
 * 
 */
export type GymSubscriptionModel = runtime.Types.Result.DefaultSelection<Prisma.$GymSubscriptionPayload>

export type AggregateGymSubscription = {
  _count: GymSubscriptionCountAggregateOutputType | null
  _avg: GymSubscriptionAvgAggregateOutputType | null
  _sum: GymSubscriptionSumAggregateOutputType | null
  _min: GymSubscriptionMinAggregateOutputType | null
  _max: GymSubscriptionMaxAggregateOutputType | null
}

export type GymSubscriptionAvgAggregateOutputType = {
  price: runtime.Decimal | null
}

export type GymSubscriptionSumAggregateOutputType = {
  price: runtime.Decimal | null
}

export type GymSubscriptionMinAggregateOutputType = {
  id: string | null
  gymId: string | null
  planId: string | null
  billingCycle: $Enums.BillingCycle | null
  status: $Enums.GymSubscriptionStatus | null
  startDate: Date | null
  renewalDate: Date | null
  price: runtime.Decimal | null
  notes: string | null
  createdById: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GymSubscriptionMaxAggregateOutputType = {
  id: string | null
  gymId: string | null
  planId: string | null
  billingCycle: $Enums.BillingCycle | null
  status: $Enums.GymSubscriptionStatus | null
  startDate: Date | null
  renewalDate: Date | null
  price: runtime.Decimal | null
  notes: string | null
  createdById: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GymSubscriptionCountAggregateOutputType = {
  id: number
  gymId: number
  planId: number
  billingCycle: number
  status: number
  startDate: number
  renewalDate: number
  price: number
  notes: number
  createdById: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GymSubscriptionAvgAggregateInputType = {
  price?: true
}

export type GymSubscriptionSumAggregateInputType = {
  price?: true
}

export type GymSubscriptionMinAggregateInputType = {
  id?: true
  gymId?: true
  planId?: true
  billingCycle?: true
  status?: true
  startDate?: true
  renewalDate?: true
  price?: true
  notes?: true
  createdById?: true
  createdAt?: true
  updatedAt?: true
}

export type GymSubscriptionMaxAggregateInputType = {
  id?: true
  gymId?: true
  planId?: true
  billingCycle?: true
  status?: true
  startDate?: true
  renewalDate?: true
  price?: true
  notes?: true
  createdById?: true
  createdAt?: true
  updatedAt?: true
}

export type GymSubscriptionCountAggregateInputType = {
  id?: true
  gymId?: true
  planId?: true
  billingCycle?: true
  status?: true
  startDate?: true
  renewalDate?: true
  price?: true
  notes?: true
  createdById?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GymSubscriptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GymSubscription to aggregate.
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymSubscriptions to fetch.
   */
  orderBy?: Prisma.GymSubscriptionOrderByWithRelationInput | Prisma.GymSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GymSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GymSubscriptions
  **/
  _count?: true | GymSubscriptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GymSubscriptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GymSubscriptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GymSubscriptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GymSubscriptionMaxAggregateInputType
}

export type GetGymSubscriptionAggregateType<T extends GymSubscriptionAggregateArgs> = {
      [P in keyof T & keyof AggregateGymSubscription]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGymSubscription[P]>
    : Prisma.GetScalarType<T[P], AggregateGymSubscription[P]>
}




export type GymSubscriptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GymSubscriptionWhereInput
  orderBy?: Prisma.GymSubscriptionOrderByWithAggregationInput | Prisma.GymSubscriptionOrderByWithAggregationInput[]
  by: Prisma.GymSubscriptionScalarFieldEnum[] | Prisma.GymSubscriptionScalarFieldEnum
  having?: Prisma.GymSubscriptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GymSubscriptionCountAggregateInputType | true
  _avg?: GymSubscriptionAvgAggregateInputType
  _sum?: GymSubscriptionSumAggregateInputType
  _min?: GymSubscriptionMinAggregateInputType
  _max?: GymSubscriptionMaxAggregateInputType
}

export type GymSubscriptionGroupByOutputType = {
  id: string
  gymId: string
  planId: string
  billingCycle: $Enums.BillingCycle
  status: $Enums.GymSubscriptionStatus
  startDate: Date
  renewalDate: Date
  price: runtime.Decimal
  notes: string | null
  createdById: string | null
  createdAt: Date
  updatedAt: Date
  _count: GymSubscriptionCountAggregateOutputType | null
  _avg: GymSubscriptionAvgAggregateOutputType | null
  _sum: GymSubscriptionSumAggregateOutputType | null
  _min: GymSubscriptionMinAggregateOutputType | null
  _max: GymSubscriptionMaxAggregateOutputType | null
}

export type GetGymSubscriptionGroupByPayload<T extends GymSubscriptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GymSubscriptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GymSubscriptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GymSubscriptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GymSubscriptionGroupByOutputType[P]>
      }
    >
  >



export type GymSubscriptionWhereInput = {
  AND?: Prisma.GymSubscriptionWhereInput | Prisma.GymSubscriptionWhereInput[]
  OR?: Prisma.GymSubscriptionWhereInput[]
  NOT?: Prisma.GymSubscriptionWhereInput | Prisma.GymSubscriptionWhereInput[]
  id?: Prisma.StringFilter<"GymSubscription"> | string
  gymId?: Prisma.StringFilter<"GymSubscription"> | string
  planId?: Prisma.StringFilter<"GymSubscription"> | string
  billingCycle?: Prisma.EnumBillingCycleFilter<"GymSubscription"> | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFilter<"GymSubscription"> | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  renewalDate?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  price?: Prisma.DecimalFilter<"GymSubscription"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableFilter<"GymSubscription"> | string | null
  createdById?: Prisma.StringNullableFilter<"GymSubscription"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  gym?: Prisma.XOR<Prisma.GymScalarRelationFilter, Prisma.GymWhereInput>
  plan?: Prisma.XOR<Prisma.PlanScalarRelationFilter, Prisma.PlanWhereInput>
  createdBy?: Prisma.XOR<Prisma.SuperAdminNullableScalarRelationFilter, Prisma.SuperAdminWhereInput> | null
}

export type GymSubscriptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  planId?: Prisma.SortOrder
  billingCycle?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  renewalDate?: Prisma.SortOrder
  price?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  gym?: Prisma.GymOrderByWithRelationInput
  plan?: Prisma.PlanOrderByWithRelationInput
  createdBy?: Prisma.SuperAdminOrderByWithRelationInput
}

export type GymSubscriptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GymSubscriptionWhereInput | Prisma.GymSubscriptionWhereInput[]
  OR?: Prisma.GymSubscriptionWhereInput[]
  NOT?: Prisma.GymSubscriptionWhereInput | Prisma.GymSubscriptionWhereInput[]
  gymId?: Prisma.StringFilter<"GymSubscription"> | string
  planId?: Prisma.StringFilter<"GymSubscription"> | string
  billingCycle?: Prisma.EnumBillingCycleFilter<"GymSubscription"> | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFilter<"GymSubscription"> | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  renewalDate?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  price?: Prisma.DecimalFilter<"GymSubscription"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableFilter<"GymSubscription"> | string | null
  createdById?: Prisma.StringNullableFilter<"GymSubscription"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  gym?: Prisma.XOR<Prisma.GymScalarRelationFilter, Prisma.GymWhereInput>
  plan?: Prisma.XOR<Prisma.PlanScalarRelationFilter, Prisma.PlanWhereInput>
  createdBy?: Prisma.XOR<Prisma.SuperAdminNullableScalarRelationFilter, Prisma.SuperAdminWhereInput> | null
}, "id">

export type GymSubscriptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  planId?: Prisma.SortOrder
  billingCycle?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  renewalDate?: Prisma.SortOrder
  price?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GymSubscriptionCountOrderByAggregateInput
  _avg?: Prisma.GymSubscriptionAvgOrderByAggregateInput
  _max?: Prisma.GymSubscriptionMaxOrderByAggregateInput
  _min?: Prisma.GymSubscriptionMinOrderByAggregateInput
  _sum?: Prisma.GymSubscriptionSumOrderByAggregateInput
}

export type GymSubscriptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.GymSubscriptionScalarWhereWithAggregatesInput | Prisma.GymSubscriptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.GymSubscriptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GymSubscriptionScalarWhereWithAggregatesInput | Prisma.GymSubscriptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GymSubscription"> | string
  gymId?: Prisma.StringWithAggregatesFilter<"GymSubscription"> | string
  planId?: Prisma.StringWithAggregatesFilter<"GymSubscription"> | string
  billingCycle?: Prisma.EnumBillingCycleWithAggregatesFilter<"GymSubscription"> | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusWithAggregatesFilter<"GymSubscription"> | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeWithAggregatesFilter<"GymSubscription"> | Date | string
  renewalDate?: Prisma.DateTimeWithAggregatesFilter<"GymSubscription"> | Date | string
  price?: Prisma.DecimalWithAggregatesFilter<"GymSubscription"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"GymSubscription"> | string | null
  createdById?: Prisma.StringNullableWithAggregatesFilter<"GymSubscription"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GymSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GymSubscription"> | Date | string
}

export type GymSubscriptionCreateInput = {
  id?: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  gym: Prisma.GymCreateNestedOneWithoutSubscriptionsInput
  plan: Prisma.PlanCreateNestedOneWithoutSubscriptionsInput
  createdBy?: Prisma.SuperAdminCreateNestedOneWithoutSubscriptionsInput
}

export type GymSubscriptionUncheckedCreateInput = {
  id?: string
  gymId: string
  planId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdById?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gym?: Prisma.GymUpdateOneRequiredWithoutSubscriptionsNestedInput
  plan?: Prisma.PlanUpdateOneRequiredWithoutSubscriptionsNestedInput
  createdBy?: Prisma.SuperAdminUpdateOneWithoutSubscriptionsNestedInput
}

export type GymSubscriptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  planId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionCreateManyInput = {
  id?: string
  gymId: string
  planId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdById?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  planId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionListRelationFilter = {
  every?: Prisma.GymSubscriptionWhereInput
  some?: Prisma.GymSubscriptionWhereInput
  none?: Prisma.GymSubscriptionWhereInput
}

export type GymSubscriptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GymSubscriptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  planId?: Prisma.SortOrder
  billingCycle?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  renewalDate?: Prisma.SortOrder
  price?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymSubscriptionAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type GymSubscriptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  planId?: Prisma.SortOrder
  billingCycle?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  renewalDate?: Prisma.SortOrder
  price?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymSubscriptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  planId?: Prisma.SortOrder
  billingCycle?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  renewalDate?: Prisma.SortOrder
  price?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymSubscriptionSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type GymSubscriptionCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput> | Prisma.GymSubscriptionCreateWithoutCreatedByInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput | Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.GymSubscriptionCreateManyCreatedByInputEnvelope
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
}

export type GymSubscriptionUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput> | Prisma.GymSubscriptionCreateWithoutCreatedByInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput | Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.GymSubscriptionCreateManyCreatedByInputEnvelope
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
}

export type GymSubscriptionUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput> | Prisma.GymSubscriptionCreateWithoutCreatedByInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput | Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.GymSubscriptionCreateManyCreatedByInputEnvelope
  set?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  delete?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  update?: Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.GymSubscriptionUpdateManyWithWhereWithoutCreatedByInput | Prisma.GymSubscriptionUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
}

export type GymSubscriptionUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput> | Prisma.GymSubscriptionCreateWithoutCreatedByInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput | Prisma.GymSubscriptionCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.GymSubscriptionCreateManyCreatedByInputEnvelope
  set?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  delete?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  update?: Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.GymSubscriptionUpdateManyWithWhereWithoutCreatedByInput | Prisma.GymSubscriptionUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
}

export type GymSubscriptionCreateNestedManyWithoutPlanInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutPlanInput, Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput> | Prisma.GymSubscriptionCreateWithoutPlanInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput | Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput[]
  createMany?: Prisma.GymSubscriptionCreateManyPlanInputEnvelope
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
}

export type GymSubscriptionUncheckedCreateNestedManyWithoutPlanInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutPlanInput, Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput> | Prisma.GymSubscriptionCreateWithoutPlanInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput | Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput[]
  createMany?: Prisma.GymSubscriptionCreateManyPlanInputEnvelope
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
}

export type GymSubscriptionUpdateManyWithoutPlanNestedInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutPlanInput, Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput> | Prisma.GymSubscriptionCreateWithoutPlanInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput | Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput[]
  upsert?: Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutPlanInput | Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutPlanInput[]
  createMany?: Prisma.GymSubscriptionCreateManyPlanInputEnvelope
  set?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  delete?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  update?: Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutPlanInput | Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutPlanInput[]
  updateMany?: Prisma.GymSubscriptionUpdateManyWithWhereWithoutPlanInput | Prisma.GymSubscriptionUpdateManyWithWhereWithoutPlanInput[]
  deleteMany?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
}

export type GymSubscriptionUncheckedUpdateManyWithoutPlanNestedInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutPlanInput, Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput> | Prisma.GymSubscriptionCreateWithoutPlanInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput | Prisma.GymSubscriptionCreateOrConnectWithoutPlanInput[]
  upsert?: Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutPlanInput | Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutPlanInput[]
  createMany?: Prisma.GymSubscriptionCreateManyPlanInputEnvelope
  set?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  delete?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  update?: Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutPlanInput | Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutPlanInput[]
  updateMany?: Prisma.GymSubscriptionUpdateManyWithWhereWithoutPlanInput | Prisma.GymSubscriptionUpdateManyWithWhereWithoutPlanInput[]
  deleteMany?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
}

export type GymSubscriptionCreateNestedManyWithoutGymInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutGymInput, Prisma.GymSubscriptionUncheckedCreateWithoutGymInput> | Prisma.GymSubscriptionCreateWithoutGymInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutGymInput | Prisma.GymSubscriptionCreateOrConnectWithoutGymInput[]
  createMany?: Prisma.GymSubscriptionCreateManyGymInputEnvelope
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
}

export type GymSubscriptionUncheckedCreateNestedManyWithoutGymInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutGymInput, Prisma.GymSubscriptionUncheckedCreateWithoutGymInput> | Prisma.GymSubscriptionCreateWithoutGymInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutGymInput | Prisma.GymSubscriptionCreateOrConnectWithoutGymInput[]
  createMany?: Prisma.GymSubscriptionCreateManyGymInputEnvelope
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
}

export type GymSubscriptionUpdateManyWithoutGymNestedInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutGymInput, Prisma.GymSubscriptionUncheckedCreateWithoutGymInput> | Prisma.GymSubscriptionCreateWithoutGymInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutGymInput | Prisma.GymSubscriptionCreateOrConnectWithoutGymInput[]
  upsert?: Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutGymInput | Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutGymInput[]
  createMany?: Prisma.GymSubscriptionCreateManyGymInputEnvelope
  set?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  delete?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  update?: Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutGymInput | Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutGymInput[]
  updateMany?: Prisma.GymSubscriptionUpdateManyWithWhereWithoutGymInput | Prisma.GymSubscriptionUpdateManyWithWhereWithoutGymInput[]
  deleteMany?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
}

export type GymSubscriptionUncheckedUpdateManyWithoutGymNestedInput = {
  create?: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutGymInput, Prisma.GymSubscriptionUncheckedCreateWithoutGymInput> | Prisma.GymSubscriptionCreateWithoutGymInput[] | Prisma.GymSubscriptionUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymSubscriptionCreateOrConnectWithoutGymInput | Prisma.GymSubscriptionCreateOrConnectWithoutGymInput[]
  upsert?: Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutGymInput | Prisma.GymSubscriptionUpsertWithWhereUniqueWithoutGymInput[]
  createMany?: Prisma.GymSubscriptionCreateManyGymInputEnvelope
  set?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  disconnect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  delete?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  connect?: Prisma.GymSubscriptionWhereUniqueInput | Prisma.GymSubscriptionWhereUniqueInput[]
  update?: Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutGymInput | Prisma.GymSubscriptionUpdateWithWhereUniqueWithoutGymInput[]
  updateMany?: Prisma.GymSubscriptionUpdateManyWithWhereWithoutGymInput | Prisma.GymSubscriptionUpdateManyWithWhereWithoutGymInput[]
  deleteMany?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
}

export type EnumBillingCycleFieldUpdateOperationsInput = {
  set?: $Enums.BillingCycle
}

export type EnumGymSubscriptionStatusFieldUpdateOperationsInput = {
  set?: $Enums.GymSubscriptionStatus
}

export type GymSubscriptionCreateWithoutCreatedByInput = {
  id?: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  gym: Prisma.GymCreateNestedOneWithoutSubscriptionsInput
  plan: Prisma.PlanCreateNestedOneWithoutSubscriptionsInput
}

export type GymSubscriptionUncheckedCreateWithoutCreatedByInput = {
  id?: string
  gymId: string
  planId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  create: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput>
}

export type GymSubscriptionCreateManyCreatedByInputEnvelope = {
  data: Prisma.GymSubscriptionCreateManyCreatedByInput | Prisma.GymSubscriptionCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type GymSubscriptionUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  update: Prisma.XOR<Prisma.GymSubscriptionUpdateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedCreateWithoutCreatedByInput>
}

export type GymSubscriptionUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateWithoutCreatedByInput, Prisma.GymSubscriptionUncheckedUpdateWithoutCreatedByInput>
}

export type GymSubscriptionUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.GymSubscriptionScalarWhereInput
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateManyMutationInput, Prisma.GymSubscriptionUncheckedUpdateManyWithoutCreatedByInput>
}

export type GymSubscriptionScalarWhereInput = {
  AND?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
  OR?: Prisma.GymSubscriptionScalarWhereInput[]
  NOT?: Prisma.GymSubscriptionScalarWhereInput | Prisma.GymSubscriptionScalarWhereInput[]
  id?: Prisma.StringFilter<"GymSubscription"> | string
  gymId?: Prisma.StringFilter<"GymSubscription"> | string
  planId?: Prisma.StringFilter<"GymSubscription"> | string
  billingCycle?: Prisma.EnumBillingCycleFilter<"GymSubscription"> | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFilter<"GymSubscription"> | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  renewalDate?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  price?: Prisma.DecimalFilter<"GymSubscription"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableFilter<"GymSubscription"> | string | null
  createdById?: Prisma.StringNullableFilter<"GymSubscription"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GymSubscription"> | Date | string
}

export type GymSubscriptionCreateWithoutPlanInput = {
  id?: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  gym: Prisma.GymCreateNestedOneWithoutSubscriptionsInput
  createdBy?: Prisma.SuperAdminCreateNestedOneWithoutSubscriptionsInput
}

export type GymSubscriptionUncheckedCreateWithoutPlanInput = {
  id?: string
  gymId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdById?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionCreateOrConnectWithoutPlanInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  create: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutPlanInput, Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput>
}

export type GymSubscriptionCreateManyPlanInputEnvelope = {
  data: Prisma.GymSubscriptionCreateManyPlanInput | Prisma.GymSubscriptionCreateManyPlanInput[]
  skipDuplicates?: boolean
}

export type GymSubscriptionUpsertWithWhereUniqueWithoutPlanInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  update: Prisma.XOR<Prisma.GymSubscriptionUpdateWithoutPlanInput, Prisma.GymSubscriptionUncheckedUpdateWithoutPlanInput>
  create: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutPlanInput, Prisma.GymSubscriptionUncheckedCreateWithoutPlanInput>
}

export type GymSubscriptionUpdateWithWhereUniqueWithoutPlanInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateWithoutPlanInput, Prisma.GymSubscriptionUncheckedUpdateWithoutPlanInput>
}

export type GymSubscriptionUpdateManyWithWhereWithoutPlanInput = {
  where: Prisma.GymSubscriptionScalarWhereInput
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateManyMutationInput, Prisma.GymSubscriptionUncheckedUpdateManyWithoutPlanInput>
}

export type GymSubscriptionCreateWithoutGymInput = {
  id?: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  plan: Prisma.PlanCreateNestedOneWithoutSubscriptionsInput
  createdBy?: Prisma.SuperAdminCreateNestedOneWithoutSubscriptionsInput
}

export type GymSubscriptionUncheckedCreateWithoutGymInput = {
  id?: string
  planId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdById?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionCreateOrConnectWithoutGymInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  create: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutGymInput, Prisma.GymSubscriptionUncheckedCreateWithoutGymInput>
}

export type GymSubscriptionCreateManyGymInputEnvelope = {
  data: Prisma.GymSubscriptionCreateManyGymInput | Prisma.GymSubscriptionCreateManyGymInput[]
  skipDuplicates?: boolean
}

export type GymSubscriptionUpsertWithWhereUniqueWithoutGymInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  update: Prisma.XOR<Prisma.GymSubscriptionUpdateWithoutGymInput, Prisma.GymSubscriptionUncheckedUpdateWithoutGymInput>
  create: Prisma.XOR<Prisma.GymSubscriptionCreateWithoutGymInput, Prisma.GymSubscriptionUncheckedCreateWithoutGymInput>
}

export type GymSubscriptionUpdateWithWhereUniqueWithoutGymInput = {
  where: Prisma.GymSubscriptionWhereUniqueInput
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateWithoutGymInput, Prisma.GymSubscriptionUncheckedUpdateWithoutGymInput>
}

export type GymSubscriptionUpdateManyWithWhereWithoutGymInput = {
  where: Prisma.GymSubscriptionScalarWhereInput
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateManyMutationInput, Prisma.GymSubscriptionUncheckedUpdateManyWithoutGymInput>
}

export type GymSubscriptionCreateManyCreatedByInput = {
  id?: string
  gymId: string
  planId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gym?: Prisma.GymUpdateOneRequiredWithoutSubscriptionsNestedInput
  plan?: Prisma.PlanUpdateOneRequiredWithoutSubscriptionsNestedInput
}

export type GymSubscriptionUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  planId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  planId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionCreateManyPlanInput = {
  id?: string
  gymId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdById?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionUpdateWithoutPlanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gym?: Prisma.GymUpdateOneRequiredWithoutSubscriptionsNestedInput
  createdBy?: Prisma.SuperAdminUpdateOneWithoutSubscriptionsNestedInput
}

export type GymSubscriptionUncheckedUpdateWithoutPlanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionUncheckedUpdateManyWithoutPlanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionCreateManyGymInput = {
  id?: string
  planId: string
  billingCycle?: $Enums.BillingCycle
  status?: $Enums.GymSubscriptionStatus
  startDate?: Date | string
  renewalDate: Date | string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  createdById?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymSubscriptionUpdateWithoutGymInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plan?: Prisma.PlanUpdateOneRequiredWithoutSubscriptionsNestedInput
  createdBy?: Prisma.SuperAdminUpdateOneWithoutSubscriptionsNestedInput
}

export type GymSubscriptionUncheckedUpdateWithoutGymInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  planId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymSubscriptionUncheckedUpdateManyWithoutGymInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  planId?: Prisma.StringFieldUpdateOperationsInput | string
  billingCycle?: Prisma.EnumBillingCycleFieldUpdateOperationsInput | $Enums.BillingCycle
  status?: Prisma.EnumGymSubscriptionStatusFieldUpdateOperationsInput | $Enums.GymSubscriptionStatus
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  renewalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GymSubscriptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gymId?: boolean
  planId?: boolean
  billingCycle?: boolean
  status?: boolean
  startDate?: boolean
  renewalDate?: boolean
  price?: boolean
  notes?: boolean
  createdById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  plan?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.GymSubscription$createdByArgs<ExtArgs>
}, ExtArgs["result"]["gymSubscription"]>

export type GymSubscriptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gymId?: boolean
  planId?: boolean
  billingCycle?: boolean
  status?: boolean
  startDate?: boolean
  renewalDate?: boolean
  price?: boolean
  notes?: boolean
  createdById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  plan?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.GymSubscription$createdByArgs<ExtArgs>
}, ExtArgs["result"]["gymSubscription"]>

export type GymSubscriptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gymId?: boolean
  planId?: boolean
  billingCycle?: boolean
  status?: boolean
  startDate?: boolean
  renewalDate?: boolean
  price?: boolean
  notes?: boolean
  createdById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  plan?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.GymSubscription$createdByArgs<ExtArgs>
}, ExtArgs["result"]["gymSubscription"]>

export type GymSubscriptionSelectScalar = {
  id?: boolean
  gymId?: boolean
  planId?: boolean
  billingCycle?: boolean
  status?: boolean
  startDate?: boolean
  renewalDate?: boolean
  price?: boolean
  notes?: boolean
  createdById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GymSubscriptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gymId" | "planId" | "billingCycle" | "status" | "startDate" | "renewalDate" | "price" | "notes" | "createdById" | "createdAt" | "updatedAt", ExtArgs["result"]["gymSubscription"]>
export type GymSubscriptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  plan?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.GymSubscription$createdByArgs<ExtArgs>
}
export type GymSubscriptionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  plan?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.GymSubscription$createdByArgs<ExtArgs>
}
export type GymSubscriptionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  plan?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.GymSubscription$createdByArgs<ExtArgs>
}

export type $GymSubscriptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GymSubscription"
  objects: {
    gym: Prisma.$GymPayload<ExtArgs>
    plan: Prisma.$PlanPayload<ExtArgs>
    createdBy: Prisma.$SuperAdminPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    gymId: string
    planId: string
    billingCycle: $Enums.BillingCycle
    status: $Enums.GymSubscriptionStatus
    startDate: Date
    renewalDate: Date
    price: runtime.Decimal
    notes: string | null
    createdById: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["gymSubscription"]>
  composites: {}
}

export type GymSubscriptionGetPayload<S extends boolean | null | undefined | GymSubscriptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload, S>

export type GymSubscriptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GymSubscriptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GymSubscriptionCountAggregateInputType | true
  }

export interface GymSubscriptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GymSubscription'], meta: { name: 'GymSubscription' } }
  /**
   * Find zero or one GymSubscription that matches the filter.
   * @param {GymSubscriptionFindUniqueArgs} args - Arguments to find a GymSubscription
   * @example
   * // Get one GymSubscription
   * const gymSubscription = await prisma.gymSubscription.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GymSubscriptionFindUniqueArgs>(args: Prisma.SelectSubset<T, GymSubscriptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GymSubscription that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GymSubscriptionFindUniqueOrThrowArgs} args - Arguments to find a GymSubscription
   * @example
   * // Get one GymSubscription
   * const gymSubscription = await prisma.gymSubscription.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GymSubscriptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GymSubscriptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GymSubscription that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionFindFirstArgs} args - Arguments to find a GymSubscription
   * @example
   * // Get one GymSubscription
   * const gymSubscription = await prisma.gymSubscription.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GymSubscriptionFindFirstArgs>(args?: Prisma.SelectSubset<T, GymSubscriptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GymSubscription that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionFindFirstOrThrowArgs} args - Arguments to find a GymSubscription
   * @example
   * // Get one GymSubscription
   * const gymSubscription = await prisma.gymSubscription.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GymSubscriptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GymSubscriptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GymSubscriptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GymSubscriptions
   * const gymSubscriptions = await prisma.gymSubscription.findMany()
   * 
   * // Get first 10 GymSubscriptions
   * const gymSubscriptions = await prisma.gymSubscription.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gymSubscriptionWithIdOnly = await prisma.gymSubscription.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GymSubscriptionFindManyArgs>(args?: Prisma.SelectSubset<T, GymSubscriptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GymSubscription.
   * @param {GymSubscriptionCreateArgs} args - Arguments to create a GymSubscription.
   * @example
   * // Create one GymSubscription
   * const GymSubscription = await prisma.gymSubscription.create({
   *   data: {
   *     // ... data to create a GymSubscription
   *   }
   * })
   * 
   */
  create<T extends GymSubscriptionCreateArgs>(args: Prisma.SelectSubset<T, GymSubscriptionCreateArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GymSubscriptions.
   * @param {GymSubscriptionCreateManyArgs} args - Arguments to create many GymSubscriptions.
   * @example
   * // Create many GymSubscriptions
   * const gymSubscription = await prisma.gymSubscription.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GymSubscriptionCreateManyArgs>(args?: Prisma.SelectSubset<T, GymSubscriptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GymSubscriptions and returns the data saved in the database.
   * @param {GymSubscriptionCreateManyAndReturnArgs} args - Arguments to create many GymSubscriptions.
   * @example
   * // Create many GymSubscriptions
   * const gymSubscription = await prisma.gymSubscription.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GymSubscriptions and only return the `id`
   * const gymSubscriptionWithIdOnly = await prisma.gymSubscription.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GymSubscriptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GymSubscriptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GymSubscription.
   * @param {GymSubscriptionDeleteArgs} args - Arguments to delete one GymSubscription.
   * @example
   * // Delete one GymSubscription
   * const GymSubscription = await prisma.gymSubscription.delete({
   *   where: {
   *     // ... filter to delete one GymSubscription
   *   }
   * })
   * 
   */
  delete<T extends GymSubscriptionDeleteArgs>(args: Prisma.SelectSubset<T, GymSubscriptionDeleteArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GymSubscription.
   * @param {GymSubscriptionUpdateArgs} args - Arguments to update one GymSubscription.
   * @example
   * // Update one GymSubscription
   * const gymSubscription = await prisma.gymSubscription.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GymSubscriptionUpdateArgs>(args: Prisma.SelectSubset<T, GymSubscriptionUpdateArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GymSubscriptions.
   * @param {GymSubscriptionDeleteManyArgs} args - Arguments to filter GymSubscriptions to delete.
   * @example
   * // Delete a few GymSubscriptions
   * const { count } = await prisma.gymSubscription.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GymSubscriptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, GymSubscriptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GymSubscriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GymSubscriptions
   * const gymSubscription = await prisma.gymSubscription.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GymSubscriptionUpdateManyArgs>(args: Prisma.SelectSubset<T, GymSubscriptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GymSubscriptions and returns the data updated in the database.
   * @param {GymSubscriptionUpdateManyAndReturnArgs} args - Arguments to update many GymSubscriptions.
   * @example
   * // Update many GymSubscriptions
   * const gymSubscription = await prisma.gymSubscription.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GymSubscriptions and only return the `id`
   * const gymSubscriptionWithIdOnly = await prisma.gymSubscription.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GymSubscriptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GymSubscriptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GymSubscription.
   * @param {GymSubscriptionUpsertArgs} args - Arguments to update or create a GymSubscription.
   * @example
   * // Update or create a GymSubscription
   * const gymSubscription = await prisma.gymSubscription.upsert({
   *   create: {
   *     // ... data to create a GymSubscription
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GymSubscription we want to update
   *   }
   * })
   */
  upsert<T extends GymSubscriptionUpsertArgs>(args: Prisma.SelectSubset<T, GymSubscriptionUpsertArgs<ExtArgs>>): Prisma.Prisma__GymSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$GymSubscriptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GymSubscriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionCountArgs} args - Arguments to filter GymSubscriptions to count.
   * @example
   * // Count the number of GymSubscriptions
   * const count = await prisma.gymSubscription.count({
   *   where: {
   *     // ... the filter for the GymSubscriptions we want to count
   *   }
   * })
  **/
  count<T extends GymSubscriptionCountArgs>(
    args?: Prisma.Subset<T, GymSubscriptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GymSubscriptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GymSubscription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GymSubscriptionAggregateArgs>(args: Prisma.Subset<T, GymSubscriptionAggregateArgs>): Prisma.PrismaPromise<GetGymSubscriptionAggregateType<T>>

  /**
   * Group by GymSubscription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymSubscriptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GymSubscriptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GymSubscriptionGroupByArgs['orderBy'] }
      : { orderBy?: GymSubscriptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GymSubscriptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGymSubscriptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GymSubscription model
 */
readonly fields: GymSubscriptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GymSubscription.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GymSubscriptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  gym<T extends Prisma.GymDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GymDefaultArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  plan<T extends Prisma.PlanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlanDefaultArgs<ExtArgs>>): Prisma.Prisma__PlanClient<runtime.Types.Result.GetResult<Prisma.$PlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  createdBy<T extends Prisma.GymSubscription$createdByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GymSubscription$createdByArgs<ExtArgs>>): Prisma.Prisma__SuperAdminClient<runtime.Types.Result.GetResult<Prisma.$SuperAdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GymSubscription model
 */
export interface GymSubscriptionFieldRefs {
  readonly id: Prisma.FieldRef<"GymSubscription", 'String'>
  readonly gymId: Prisma.FieldRef<"GymSubscription", 'String'>
  readonly planId: Prisma.FieldRef<"GymSubscription", 'String'>
  readonly billingCycle: Prisma.FieldRef<"GymSubscription", 'BillingCycle'>
  readonly status: Prisma.FieldRef<"GymSubscription", 'GymSubscriptionStatus'>
  readonly startDate: Prisma.FieldRef<"GymSubscription", 'DateTime'>
  readonly renewalDate: Prisma.FieldRef<"GymSubscription", 'DateTime'>
  readonly price: Prisma.FieldRef<"GymSubscription", 'Decimal'>
  readonly notes: Prisma.FieldRef<"GymSubscription", 'String'>
  readonly createdById: Prisma.FieldRef<"GymSubscription", 'String'>
  readonly createdAt: Prisma.FieldRef<"GymSubscription", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GymSubscription", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GymSubscription findUnique
 */
export type GymSubscriptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which GymSubscription to fetch.
   */
  where: Prisma.GymSubscriptionWhereUniqueInput
}

/**
 * GymSubscription findUniqueOrThrow
 */
export type GymSubscriptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which GymSubscription to fetch.
   */
  where: Prisma.GymSubscriptionWhereUniqueInput
}

/**
 * GymSubscription findFirst
 */
export type GymSubscriptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which GymSubscription to fetch.
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymSubscriptions to fetch.
   */
  orderBy?: Prisma.GymSubscriptionOrderByWithRelationInput | Prisma.GymSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GymSubscriptions.
   */
  cursor?: Prisma.GymSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GymSubscriptions.
   */
  distinct?: Prisma.GymSubscriptionScalarFieldEnum | Prisma.GymSubscriptionScalarFieldEnum[]
}

/**
 * GymSubscription findFirstOrThrow
 */
export type GymSubscriptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which GymSubscription to fetch.
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymSubscriptions to fetch.
   */
  orderBy?: Prisma.GymSubscriptionOrderByWithRelationInput | Prisma.GymSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GymSubscriptions.
   */
  cursor?: Prisma.GymSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GymSubscriptions.
   */
  distinct?: Prisma.GymSubscriptionScalarFieldEnum | Prisma.GymSubscriptionScalarFieldEnum[]
}

/**
 * GymSubscription findMany
 */
export type GymSubscriptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which GymSubscriptions to fetch.
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymSubscriptions to fetch.
   */
  orderBy?: Prisma.GymSubscriptionOrderByWithRelationInput | Prisma.GymSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GymSubscriptions.
   */
  cursor?: Prisma.GymSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GymSubscriptions.
   */
  distinct?: Prisma.GymSubscriptionScalarFieldEnum | Prisma.GymSubscriptionScalarFieldEnum[]
}

/**
 * GymSubscription create
 */
export type GymSubscriptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * The data needed to create a GymSubscription.
   */
  data: Prisma.XOR<Prisma.GymSubscriptionCreateInput, Prisma.GymSubscriptionUncheckedCreateInput>
}

/**
 * GymSubscription createMany
 */
export type GymSubscriptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GymSubscriptions.
   */
  data: Prisma.GymSubscriptionCreateManyInput | Prisma.GymSubscriptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GymSubscription createManyAndReturn
 */
export type GymSubscriptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * The data used to create many GymSubscriptions.
   */
  data: Prisma.GymSubscriptionCreateManyInput | Prisma.GymSubscriptionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GymSubscription update
 */
export type GymSubscriptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * The data needed to update a GymSubscription.
   */
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateInput, Prisma.GymSubscriptionUncheckedUpdateInput>
  /**
   * Choose, which GymSubscription to update.
   */
  where: Prisma.GymSubscriptionWhereUniqueInput
}

/**
 * GymSubscription updateMany
 */
export type GymSubscriptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GymSubscriptions.
   */
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateManyMutationInput, Prisma.GymSubscriptionUncheckedUpdateManyInput>
  /**
   * Filter which GymSubscriptions to update
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * Limit how many GymSubscriptions to update.
   */
  limit?: number
}

/**
 * GymSubscription updateManyAndReturn
 */
export type GymSubscriptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * The data used to update GymSubscriptions.
   */
  data: Prisma.XOR<Prisma.GymSubscriptionUpdateManyMutationInput, Prisma.GymSubscriptionUncheckedUpdateManyInput>
  /**
   * Filter which GymSubscriptions to update
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * Limit how many GymSubscriptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GymSubscription upsert
 */
export type GymSubscriptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * The filter to search for the GymSubscription to update in case it exists.
   */
  where: Prisma.GymSubscriptionWhereUniqueInput
  /**
   * In case the GymSubscription found by the `where` argument doesn't exist, create a new GymSubscription with this data.
   */
  create: Prisma.XOR<Prisma.GymSubscriptionCreateInput, Prisma.GymSubscriptionUncheckedCreateInput>
  /**
   * In case the GymSubscription was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GymSubscriptionUpdateInput, Prisma.GymSubscriptionUncheckedUpdateInput>
}

/**
 * GymSubscription delete
 */
export type GymSubscriptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
  /**
   * Filter which GymSubscription to delete.
   */
  where: Prisma.GymSubscriptionWhereUniqueInput
}

/**
 * GymSubscription deleteMany
 */
export type GymSubscriptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GymSubscriptions to delete
   */
  where?: Prisma.GymSubscriptionWhereInput
  /**
   * Limit how many GymSubscriptions to delete.
   */
  limit?: number
}

/**
 * GymSubscription.createdBy
 */
export type GymSubscription$createdByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuperAdmin
   */
  select?: Prisma.SuperAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuperAdmin
   */
  omit?: Prisma.SuperAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuperAdminInclude<ExtArgs> | null
  where?: Prisma.SuperAdminWhereInput
}

/**
 * GymSubscription without action
 */
export type GymSubscriptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymSubscription
   */
  select?: Prisma.GymSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymSubscription
   */
  omit?: Prisma.GymSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymSubscriptionInclude<ExtArgs> | null
}
