
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GymUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GymUser
 * 
 */
export type GymUserModel = runtime.Types.Result.DefaultSelection<Prisma.$GymUserPayload>

export type AggregateGymUser = {
  _count: GymUserCountAggregateOutputType | null
  _min: GymUserMinAggregateOutputType | null
  _max: GymUserMaxAggregateOutputType | null
}

export type GymUserMinAggregateOutputType = {
  id: string | null
  gymId: string | null
  userId: string | null
  role: $Enums.GymRole | null
  status: $Enums.UserStatus | null
  designation: string | null
  isPrimary: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GymUserMaxAggregateOutputType = {
  id: string | null
  gymId: string | null
  userId: string | null
  role: $Enums.GymRole | null
  status: $Enums.UserStatus | null
  designation: string | null
  isPrimary: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GymUserCountAggregateOutputType = {
  id: number
  gymId: number
  userId: number
  role: number
  status: number
  designation: number
  permissions: number
  isPrimary: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GymUserMinAggregateInputType = {
  id?: true
  gymId?: true
  userId?: true
  role?: true
  status?: true
  designation?: true
  isPrimary?: true
  createdAt?: true
  updatedAt?: true
}

export type GymUserMaxAggregateInputType = {
  id?: true
  gymId?: true
  userId?: true
  role?: true
  status?: true
  designation?: true
  isPrimary?: true
  createdAt?: true
  updatedAt?: true
}

export type GymUserCountAggregateInputType = {
  id?: true
  gymId?: true
  userId?: true
  role?: true
  status?: true
  designation?: true
  permissions?: true
  isPrimary?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GymUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GymUser to aggregate.
   */
  where?: Prisma.GymUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymUsers to fetch.
   */
  orderBy?: Prisma.GymUserOrderByWithRelationInput | Prisma.GymUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GymUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GymUsers
  **/
  _count?: true | GymUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GymUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GymUserMaxAggregateInputType
}

export type GetGymUserAggregateType<T extends GymUserAggregateArgs> = {
      [P in keyof T & keyof AggregateGymUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGymUser[P]>
    : Prisma.GetScalarType<T[P], AggregateGymUser[P]>
}




export type GymUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GymUserWhereInput
  orderBy?: Prisma.GymUserOrderByWithAggregationInput | Prisma.GymUserOrderByWithAggregationInput[]
  by: Prisma.GymUserScalarFieldEnum[] | Prisma.GymUserScalarFieldEnum
  having?: Prisma.GymUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GymUserCountAggregateInputType | true
  _min?: GymUserMinAggregateInputType
  _max?: GymUserMaxAggregateInputType
}

export type GymUserGroupByOutputType = {
  id: string
  gymId: string
  userId: string
  role: $Enums.GymRole
  status: $Enums.UserStatus
  designation: string | null
  permissions: runtime.JsonValue | null
  isPrimary: boolean
  createdAt: Date
  updatedAt: Date
  _count: GymUserCountAggregateOutputType | null
  _min: GymUserMinAggregateOutputType | null
  _max: GymUserMaxAggregateOutputType | null
}

export type GetGymUserGroupByPayload<T extends GymUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GymUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GymUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GymUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GymUserGroupByOutputType[P]>
      }
    >
  >



export type GymUserWhereInput = {
  AND?: Prisma.GymUserWhereInput | Prisma.GymUserWhereInput[]
  OR?: Prisma.GymUserWhereInput[]
  NOT?: Prisma.GymUserWhereInput | Prisma.GymUserWhereInput[]
  id?: Prisma.StringFilter<"GymUser"> | string
  gymId?: Prisma.StringFilter<"GymUser"> | string
  userId?: Prisma.StringFilter<"GymUser"> | string
  role?: Prisma.EnumGymRoleFilter<"GymUser"> | $Enums.GymRole
  status?: Prisma.EnumUserStatusFilter<"GymUser"> | $Enums.UserStatus
  designation?: Prisma.StringNullableFilter<"GymUser"> | string | null
  permissions?: Prisma.JsonNullableFilter<"GymUser">
  isPrimary?: Prisma.BoolFilter<"GymUser"> | boolean
  createdAt?: Prisma.DateTimeFilter<"GymUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GymUser"> | Date | string
  gym?: Prisma.XOR<Prisma.GymScalarRelationFilter, Prisma.GymWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type GymUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
  designation?: Prisma.SortOrderInput | Prisma.SortOrder
  permissions?: Prisma.SortOrderInput | Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  gym?: Prisma.GymOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type GymUserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  gymId_userId?: Prisma.GymUserGymIdUserIdCompoundUniqueInput
  AND?: Prisma.GymUserWhereInput | Prisma.GymUserWhereInput[]
  OR?: Prisma.GymUserWhereInput[]
  NOT?: Prisma.GymUserWhereInput | Prisma.GymUserWhereInput[]
  gymId?: Prisma.StringFilter<"GymUser"> | string
  userId?: Prisma.StringFilter<"GymUser"> | string
  role?: Prisma.EnumGymRoleFilter<"GymUser"> | $Enums.GymRole
  status?: Prisma.EnumUserStatusFilter<"GymUser"> | $Enums.UserStatus
  designation?: Prisma.StringNullableFilter<"GymUser"> | string | null
  permissions?: Prisma.JsonNullableFilter<"GymUser">
  isPrimary?: Prisma.BoolFilter<"GymUser"> | boolean
  createdAt?: Prisma.DateTimeFilter<"GymUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GymUser"> | Date | string
  gym?: Prisma.XOR<Prisma.GymScalarRelationFilter, Prisma.GymWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "gymId_userId">

export type GymUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
  designation?: Prisma.SortOrderInput | Prisma.SortOrder
  permissions?: Prisma.SortOrderInput | Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GymUserCountOrderByAggregateInput
  _max?: Prisma.GymUserMaxOrderByAggregateInput
  _min?: Prisma.GymUserMinOrderByAggregateInput
}

export type GymUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.GymUserScalarWhereWithAggregatesInput | Prisma.GymUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.GymUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GymUserScalarWhereWithAggregatesInput | Prisma.GymUserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GymUser"> | string
  gymId?: Prisma.StringWithAggregatesFilter<"GymUser"> | string
  userId?: Prisma.StringWithAggregatesFilter<"GymUser"> | string
  role?: Prisma.EnumGymRoleWithAggregatesFilter<"GymUser"> | $Enums.GymRole
  status?: Prisma.EnumUserStatusWithAggregatesFilter<"GymUser"> | $Enums.UserStatus
  designation?: Prisma.StringNullableWithAggregatesFilter<"GymUser"> | string | null
  permissions?: Prisma.JsonNullableWithAggregatesFilter<"GymUser">
  isPrimary?: Prisma.BoolWithAggregatesFilter<"GymUser"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GymUser"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GymUser"> | Date | string
}

export type GymUserCreateInput = {
  id?: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  gym: Prisma.GymCreateNestedOneWithoutUsersInput
  user: Prisma.UserCreateNestedOneWithoutGymMembershipsInput
}

export type GymUserUncheckedCreateInput = {
  id?: string
  gymId: string
  userId: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gym?: Prisma.GymUpdateOneRequiredWithoutUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutGymMembershipsNestedInput
}

export type GymUserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUserCreateManyInput = {
  id?: string
  gymId: string
  userId: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUserListRelationFilter = {
  every?: Prisma.GymUserWhereInput
  some?: Prisma.GymUserWhereInput
  none?: Prisma.GymUserWhereInput
}

export type GymUserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GymUserGymIdUserIdCompoundUniqueInput = {
  gymId: string
  userId: string
}

export type GymUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gymId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GymUserCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutUserInput, Prisma.GymUserUncheckedCreateWithoutUserInput> | Prisma.GymUserCreateWithoutUserInput[] | Prisma.GymUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutUserInput | Prisma.GymUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GymUserCreateManyUserInputEnvelope
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
}

export type GymUserUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutUserInput, Prisma.GymUserUncheckedCreateWithoutUserInput> | Prisma.GymUserCreateWithoutUserInput[] | Prisma.GymUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutUserInput | Prisma.GymUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GymUserCreateManyUserInputEnvelope
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
}

export type GymUserUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutUserInput, Prisma.GymUserUncheckedCreateWithoutUserInput> | Prisma.GymUserCreateWithoutUserInput[] | Prisma.GymUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutUserInput | Prisma.GymUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GymUserUpsertWithWhereUniqueWithoutUserInput | Prisma.GymUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GymUserCreateManyUserInputEnvelope
  set?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  disconnect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  delete?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  update?: Prisma.GymUserUpdateWithWhereUniqueWithoutUserInput | Prisma.GymUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GymUserUpdateManyWithWhereWithoutUserInput | Prisma.GymUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GymUserScalarWhereInput | Prisma.GymUserScalarWhereInput[]
}

export type GymUserUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutUserInput, Prisma.GymUserUncheckedCreateWithoutUserInput> | Prisma.GymUserCreateWithoutUserInput[] | Prisma.GymUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutUserInput | Prisma.GymUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GymUserUpsertWithWhereUniqueWithoutUserInput | Prisma.GymUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GymUserCreateManyUserInputEnvelope
  set?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  disconnect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  delete?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  update?: Prisma.GymUserUpdateWithWhereUniqueWithoutUserInput | Prisma.GymUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GymUserUpdateManyWithWhereWithoutUserInput | Prisma.GymUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GymUserScalarWhereInput | Prisma.GymUserScalarWhereInput[]
}

export type EnumGymRoleFieldUpdateOperationsInput = {
  set?: $Enums.GymRole
}

export type GymUserCreateNestedManyWithoutGymInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutGymInput, Prisma.GymUserUncheckedCreateWithoutGymInput> | Prisma.GymUserCreateWithoutGymInput[] | Prisma.GymUserUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutGymInput | Prisma.GymUserCreateOrConnectWithoutGymInput[]
  createMany?: Prisma.GymUserCreateManyGymInputEnvelope
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
}

export type GymUserUncheckedCreateNestedManyWithoutGymInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutGymInput, Prisma.GymUserUncheckedCreateWithoutGymInput> | Prisma.GymUserCreateWithoutGymInput[] | Prisma.GymUserUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutGymInput | Prisma.GymUserCreateOrConnectWithoutGymInput[]
  createMany?: Prisma.GymUserCreateManyGymInputEnvelope
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
}

export type GymUserUpdateManyWithoutGymNestedInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutGymInput, Prisma.GymUserUncheckedCreateWithoutGymInput> | Prisma.GymUserCreateWithoutGymInput[] | Prisma.GymUserUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutGymInput | Prisma.GymUserCreateOrConnectWithoutGymInput[]
  upsert?: Prisma.GymUserUpsertWithWhereUniqueWithoutGymInput | Prisma.GymUserUpsertWithWhereUniqueWithoutGymInput[]
  createMany?: Prisma.GymUserCreateManyGymInputEnvelope
  set?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  disconnect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  delete?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  update?: Prisma.GymUserUpdateWithWhereUniqueWithoutGymInput | Prisma.GymUserUpdateWithWhereUniqueWithoutGymInput[]
  updateMany?: Prisma.GymUserUpdateManyWithWhereWithoutGymInput | Prisma.GymUserUpdateManyWithWhereWithoutGymInput[]
  deleteMany?: Prisma.GymUserScalarWhereInput | Prisma.GymUserScalarWhereInput[]
}

export type GymUserUncheckedUpdateManyWithoutGymNestedInput = {
  create?: Prisma.XOR<Prisma.GymUserCreateWithoutGymInput, Prisma.GymUserUncheckedCreateWithoutGymInput> | Prisma.GymUserCreateWithoutGymInput[] | Prisma.GymUserUncheckedCreateWithoutGymInput[]
  connectOrCreate?: Prisma.GymUserCreateOrConnectWithoutGymInput | Prisma.GymUserCreateOrConnectWithoutGymInput[]
  upsert?: Prisma.GymUserUpsertWithWhereUniqueWithoutGymInput | Prisma.GymUserUpsertWithWhereUniqueWithoutGymInput[]
  createMany?: Prisma.GymUserCreateManyGymInputEnvelope
  set?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  disconnect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  delete?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  connect?: Prisma.GymUserWhereUniqueInput | Prisma.GymUserWhereUniqueInput[]
  update?: Prisma.GymUserUpdateWithWhereUniqueWithoutGymInput | Prisma.GymUserUpdateWithWhereUniqueWithoutGymInput[]
  updateMany?: Prisma.GymUserUpdateManyWithWhereWithoutGymInput | Prisma.GymUserUpdateManyWithWhereWithoutGymInput[]
  deleteMany?: Prisma.GymUserScalarWhereInput | Prisma.GymUserScalarWhereInput[]
}

export type GymUserCreateWithoutUserInput = {
  id?: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  gym: Prisma.GymCreateNestedOneWithoutUsersInput
}

export type GymUserUncheckedCreateWithoutUserInput = {
  id?: string
  gymId: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUserCreateOrConnectWithoutUserInput = {
  where: Prisma.GymUserWhereUniqueInput
  create: Prisma.XOR<Prisma.GymUserCreateWithoutUserInput, Prisma.GymUserUncheckedCreateWithoutUserInput>
}

export type GymUserCreateManyUserInputEnvelope = {
  data: Prisma.GymUserCreateManyUserInput | Prisma.GymUserCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type GymUserUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.GymUserWhereUniqueInput
  update: Prisma.XOR<Prisma.GymUserUpdateWithoutUserInput, Prisma.GymUserUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.GymUserCreateWithoutUserInput, Prisma.GymUserUncheckedCreateWithoutUserInput>
}

export type GymUserUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.GymUserWhereUniqueInput
  data: Prisma.XOR<Prisma.GymUserUpdateWithoutUserInput, Prisma.GymUserUncheckedUpdateWithoutUserInput>
}

export type GymUserUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.GymUserScalarWhereInput
  data: Prisma.XOR<Prisma.GymUserUpdateManyMutationInput, Prisma.GymUserUncheckedUpdateManyWithoutUserInput>
}

export type GymUserScalarWhereInput = {
  AND?: Prisma.GymUserScalarWhereInput | Prisma.GymUserScalarWhereInput[]
  OR?: Prisma.GymUserScalarWhereInput[]
  NOT?: Prisma.GymUserScalarWhereInput | Prisma.GymUserScalarWhereInput[]
  id?: Prisma.StringFilter<"GymUser"> | string
  gymId?: Prisma.StringFilter<"GymUser"> | string
  userId?: Prisma.StringFilter<"GymUser"> | string
  role?: Prisma.EnumGymRoleFilter<"GymUser"> | $Enums.GymRole
  status?: Prisma.EnumUserStatusFilter<"GymUser"> | $Enums.UserStatus
  designation?: Prisma.StringNullableFilter<"GymUser"> | string | null
  permissions?: Prisma.JsonNullableFilter<"GymUser">
  isPrimary?: Prisma.BoolFilter<"GymUser"> | boolean
  createdAt?: Prisma.DateTimeFilter<"GymUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GymUser"> | Date | string
}

export type GymUserCreateWithoutGymInput = {
  id?: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutGymMembershipsInput
}

export type GymUserUncheckedCreateWithoutGymInput = {
  id?: string
  userId: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUserCreateOrConnectWithoutGymInput = {
  where: Prisma.GymUserWhereUniqueInput
  create: Prisma.XOR<Prisma.GymUserCreateWithoutGymInput, Prisma.GymUserUncheckedCreateWithoutGymInput>
}

export type GymUserCreateManyGymInputEnvelope = {
  data: Prisma.GymUserCreateManyGymInput | Prisma.GymUserCreateManyGymInput[]
  skipDuplicates?: boolean
}

export type GymUserUpsertWithWhereUniqueWithoutGymInput = {
  where: Prisma.GymUserWhereUniqueInput
  update: Prisma.XOR<Prisma.GymUserUpdateWithoutGymInput, Prisma.GymUserUncheckedUpdateWithoutGymInput>
  create: Prisma.XOR<Prisma.GymUserCreateWithoutGymInput, Prisma.GymUserUncheckedCreateWithoutGymInput>
}

export type GymUserUpdateWithWhereUniqueWithoutGymInput = {
  where: Prisma.GymUserWhereUniqueInput
  data: Prisma.XOR<Prisma.GymUserUpdateWithoutGymInput, Prisma.GymUserUncheckedUpdateWithoutGymInput>
}

export type GymUserUpdateManyWithWhereWithoutGymInput = {
  where: Prisma.GymUserScalarWhereInput
  data: Prisma.XOR<Prisma.GymUserUpdateManyMutationInput, Prisma.GymUserUncheckedUpdateManyWithoutGymInput>
}

export type GymUserCreateManyUserInput = {
  id?: string
  gymId: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUserUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gym?: Prisma.GymUpdateOneRequiredWithoutUsersNestedInput
}

export type GymUserUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUserUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gymId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUserCreateManyGymInput = {
  id?: string
  userId: string
  role: $Enums.GymRole
  status?: $Enums.UserStatus
  designation?: string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GymUserUpdateWithoutGymInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutGymMembershipsNestedInput
}

export type GymUserUncheckedUpdateWithoutGymInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GymUserUncheckedUpdateManyWithoutGymInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumGymRoleFieldUpdateOperationsInput | $Enums.GymRole
  status?: Prisma.EnumUserStatusFieldUpdateOperationsInput | $Enums.UserStatus
  designation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GymUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gymId?: boolean
  userId?: boolean
  role?: boolean
  status?: boolean
  designation?: boolean
  permissions?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gymUser"]>

export type GymUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gymId?: boolean
  userId?: boolean
  role?: boolean
  status?: boolean
  designation?: boolean
  permissions?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gymUser"]>

export type GymUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gymId?: boolean
  userId?: boolean
  role?: boolean
  status?: boolean
  designation?: boolean
  permissions?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gymUser"]>

export type GymUserSelectScalar = {
  id?: boolean
  gymId?: boolean
  userId?: boolean
  role?: boolean
  status?: boolean
  designation?: boolean
  permissions?: boolean
  isPrimary?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GymUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gymId" | "userId" | "role" | "status" | "designation" | "permissions" | "isPrimary" | "createdAt" | "updatedAt", ExtArgs["result"]["gymUser"]>
export type GymUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type GymUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type GymUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gym?: boolean | Prisma.GymDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $GymUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GymUser"
  objects: {
    gym: Prisma.$GymPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    gymId: string
    userId: string
    role: $Enums.GymRole
    status: $Enums.UserStatus
    designation: string | null
    permissions: runtime.JsonValue | null
    isPrimary: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["gymUser"]>
  composites: {}
}

export type GymUserGetPayload<S extends boolean | null | undefined | GymUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GymUserPayload, S>

export type GymUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GymUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GymUserCountAggregateInputType | true
  }

export interface GymUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GymUser'], meta: { name: 'GymUser' } }
  /**
   * Find zero or one GymUser that matches the filter.
   * @param {GymUserFindUniqueArgs} args - Arguments to find a GymUser
   * @example
   * // Get one GymUser
   * const gymUser = await prisma.gymUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GymUserFindUniqueArgs>(args: Prisma.SelectSubset<T, GymUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GymUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GymUserFindUniqueOrThrowArgs} args - Arguments to find a GymUser
   * @example
   * // Get one GymUser
   * const gymUser = await prisma.gymUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GymUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GymUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GymUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserFindFirstArgs} args - Arguments to find a GymUser
   * @example
   * // Get one GymUser
   * const gymUser = await prisma.gymUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GymUserFindFirstArgs>(args?: Prisma.SelectSubset<T, GymUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GymUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserFindFirstOrThrowArgs} args - Arguments to find a GymUser
   * @example
   * // Get one GymUser
   * const gymUser = await prisma.gymUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GymUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GymUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GymUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GymUsers
   * const gymUsers = await prisma.gymUser.findMany()
   * 
   * // Get first 10 GymUsers
   * const gymUsers = await prisma.gymUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gymUserWithIdOnly = await prisma.gymUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GymUserFindManyArgs>(args?: Prisma.SelectSubset<T, GymUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GymUser.
   * @param {GymUserCreateArgs} args - Arguments to create a GymUser.
   * @example
   * // Create one GymUser
   * const GymUser = await prisma.gymUser.create({
   *   data: {
   *     // ... data to create a GymUser
   *   }
   * })
   * 
   */
  create<T extends GymUserCreateArgs>(args: Prisma.SelectSubset<T, GymUserCreateArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GymUsers.
   * @param {GymUserCreateManyArgs} args - Arguments to create many GymUsers.
   * @example
   * // Create many GymUsers
   * const gymUser = await prisma.gymUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GymUserCreateManyArgs>(args?: Prisma.SelectSubset<T, GymUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GymUsers and returns the data saved in the database.
   * @param {GymUserCreateManyAndReturnArgs} args - Arguments to create many GymUsers.
   * @example
   * // Create many GymUsers
   * const gymUser = await prisma.gymUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GymUsers and only return the `id`
   * const gymUserWithIdOnly = await prisma.gymUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GymUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GymUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GymUser.
   * @param {GymUserDeleteArgs} args - Arguments to delete one GymUser.
   * @example
   * // Delete one GymUser
   * const GymUser = await prisma.gymUser.delete({
   *   where: {
   *     // ... filter to delete one GymUser
   *   }
   * })
   * 
   */
  delete<T extends GymUserDeleteArgs>(args: Prisma.SelectSubset<T, GymUserDeleteArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GymUser.
   * @param {GymUserUpdateArgs} args - Arguments to update one GymUser.
   * @example
   * // Update one GymUser
   * const gymUser = await prisma.gymUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GymUserUpdateArgs>(args: Prisma.SelectSubset<T, GymUserUpdateArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GymUsers.
   * @param {GymUserDeleteManyArgs} args - Arguments to filter GymUsers to delete.
   * @example
   * // Delete a few GymUsers
   * const { count } = await prisma.gymUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GymUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, GymUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GymUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GymUsers
   * const gymUser = await prisma.gymUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GymUserUpdateManyArgs>(args: Prisma.SelectSubset<T, GymUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GymUsers and returns the data updated in the database.
   * @param {GymUserUpdateManyAndReturnArgs} args - Arguments to update many GymUsers.
   * @example
   * // Update many GymUsers
   * const gymUser = await prisma.gymUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GymUsers and only return the `id`
   * const gymUserWithIdOnly = await prisma.gymUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GymUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GymUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GymUser.
   * @param {GymUserUpsertArgs} args - Arguments to update or create a GymUser.
   * @example
   * // Update or create a GymUser
   * const gymUser = await prisma.gymUser.upsert({
   *   create: {
   *     // ... data to create a GymUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GymUser we want to update
   *   }
   * })
   */
  upsert<T extends GymUserUpsertArgs>(args: Prisma.SelectSubset<T, GymUserUpsertArgs<ExtArgs>>): Prisma.Prisma__GymUserClient<runtime.Types.Result.GetResult<Prisma.$GymUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GymUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserCountArgs} args - Arguments to filter GymUsers to count.
   * @example
   * // Count the number of GymUsers
   * const count = await prisma.gymUser.count({
   *   where: {
   *     // ... the filter for the GymUsers we want to count
   *   }
   * })
  **/
  count<T extends GymUserCountArgs>(
    args?: Prisma.Subset<T, GymUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GymUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GymUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GymUserAggregateArgs>(args: Prisma.Subset<T, GymUserAggregateArgs>): Prisma.PrismaPromise<GetGymUserAggregateType<T>>

  /**
   * Group by GymUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GymUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GymUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GymUserGroupByArgs['orderBy'] }
      : { orderBy?: GymUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GymUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGymUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GymUser model
 */
readonly fields: GymUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GymUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GymUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  gym<T extends Prisma.GymDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GymDefaultArgs<ExtArgs>>): Prisma.Prisma__GymClient<runtime.Types.Result.GetResult<Prisma.$GymPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GymUser model
 */
export interface GymUserFieldRefs {
  readonly id: Prisma.FieldRef<"GymUser", 'String'>
  readonly gymId: Prisma.FieldRef<"GymUser", 'String'>
  readonly userId: Prisma.FieldRef<"GymUser", 'String'>
  readonly role: Prisma.FieldRef<"GymUser", 'GymRole'>
  readonly status: Prisma.FieldRef<"GymUser", 'UserStatus'>
  readonly designation: Prisma.FieldRef<"GymUser", 'String'>
  readonly permissions: Prisma.FieldRef<"GymUser", 'Json'>
  readonly isPrimary: Prisma.FieldRef<"GymUser", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"GymUser", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GymUser", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GymUser findUnique
 */
export type GymUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * Filter, which GymUser to fetch.
   */
  where: Prisma.GymUserWhereUniqueInput
}

/**
 * GymUser findUniqueOrThrow
 */
export type GymUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * Filter, which GymUser to fetch.
   */
  where: Prisma.GymUserWhereUniqueInput
}

/**
 * GymUser findFirst
 */
export type GymUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * Filter, which GymUser to fetch.
   */
  where?: Prisma.GymUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymUsers to fetch.
   */
  orderBy?: Prisma.GymUserOrderByWithRelationInput | Prisma.GymUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GymUsers.
   */
  cursor?: Prisma.GymUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GymUsers.
   */
  distinct?: Prisma.GymUserScalarFieldEnum | Prisma.GymUserScalarFieldEnum[]
}

/**
 * GymUser findFirstOrThrow
 */
export type GymUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * Filter, which GymUser to fetch.
   */
  where?: Prisma.GymUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymUsers to fetch.
   */
  orderBy?: Prisma.GymUserOrderByWithRelationInput | Prisma.GymUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GymUsers.
   */
  cursor?: Prisma.GymUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GymUsers.
   */
  distinct?: Prisma.GymUserScalarFieldEnum | Prisma.GymUserScalarFieldEnum[]
}

/**
 * GymUser findMany
 */
export type GymUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * Filter, which GymUsers to fetch.
   */
  where?: Prisma.GymUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GymUsers to fetch.
   */
  orderBy?: Prisma.GymUserOrderByWithRelationInput | Prisma.GymUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GymUsers.
   */
  cursor?: Prisma.GymUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GymUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GymUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GymUsers.
   */
  distinct?: Prisma.GymUserScalarFieldEnum | Prisma.GymUserScalarFieldEnum[]
}

/**
 * GymUser create
 */
export type GymUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * The data needed to create a GymUser.
   */
  data: Prisma.XOR<Prisma.GymUserCreateInput, Prisma.GymUserUncheckedCreateInput>
}

/**
 * GymUser createMany
 */
export type GymUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GymUsers.
   */
  data: Prisma.GymUserCreateManyInput | Prisma.GymUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GymUser createManyAndReturn
 */
export type GymUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * The data used to create many GymUsers.
   */
  data: Prisma.GymUserCreateManyInput | Prisma.GymUserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GymUser update
 */
export type GymUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * The data needed to update a GymUser.
   */
  data: Prisma.XOR<Prisma.GymUserUpdateInput, Prisma.GymUserUncheckedUpdateInput>
  /**
   * Choose, which GymUser to update.
   */
  where: Prisma.GymUserWhereUniqueInput
}

/**
 * GymUser updateMany
 */
export type GymUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GymUsers.
   */
  data: Prisma.XOR<Prisma.GymUserUpdateManyMutationInput, Prisma.GymUserUncheckedUpdateManyInput>
  /**
   * Filter which GymUsers to update
   */
  where?: Prisma.GymUserWhereInput
  /**
   * Limit how many GymUsers to update.
   */
  limit?: number
}

/**
 * GymUser updateManyAndReturn
 */
export type GymUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * The data used to update GymUsers.
   */
  data: Prisma.XOR<Prisma.GymUserUpdateManyMutationInput, Prisma.GymUserUncheckedUpdateManyInput>
  /**
   * Filter which GymUsers to update
   */
  where?: Prisma.GymUserWhereInput
  /**
   * Limit how many GymUsers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GymUser upsert
 */
export type GymUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * The filter to search for the GymUser to update in case it exists.
   */
  where: Prisma.GymUserWhereUniqueInput
  /**
   * In case the GymUser found by the `where` argument doesn't exist, create a new GymUser with this data.
   */
  create: Prisma.XOR<Prisma.GymUserCreateInput, Prisma.GymUserUncheckedCreateInput>
  /**
   * In case the GymUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GymUserUpdateInput, Prisma.GymUserUncheckedUpdateInput>
}

/**
 * GymUser delete
 */
export type GymUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
  /**
   * Filter which GymUser to delete.
   */
  where: Prisma.GymUserWhereUniqueInput
}

/**
 * GymUser deleteMany
 */
export type GymUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GymUsers to delete
   */
  where?: Prisma.GymUserWhereInput
  /**
   * Limit how many GymUsers to delete.
   */
  limit?: number
}

/**
 * GymUser without action
 */
export type GymUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GymUser
   */
  select?: Prisma.GymUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GymUser
   */
  omit?: Prisma.GymUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GymUserInclude<ExtArgs> | null
}
