
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReadNotification` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReadNotification
 * 
 */
export type ReadNotificationModel = runtime.Types.Result.DefaultSelection<Prisma.$ReadNotificationPayload>

export type AggregateReadNotification = {
  _count: ReadNotificationCountAggregateOutputType | null
  _min: ReadNotificationMinAggregateOutputType | null
  _max: ReadNotificationMaxAggregateOutputType | null
}

export type ReadNotificationMinAggregateOutputType = {
  id: string | null
  readAt: Date | null
}

export type ReadNotificationMaxAggregateOutputType = {
  id: string | null
  readAt: Date | null
}

export type ReadNotificationCountAggregateOutputType = {
  id: number
  readAt: number
  _all: number
}


export type ReadNotificationMinAggregateInputType = {
  id?: true
  readAt?: true
}

export type ReadNotificationMaxAggregateInputType = {
  id?: true
  readAt?: true
}

export type ReadNotificationCountAggregateInputType = {
  id?: true
  readAt?: true
  _all?: true
}

export type ReadNotificationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReadNotification to aggregate.
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadNotifications to fetch.
   */
  orderBy?: Prisma.ReadNotificationOrderByWithRelationInput | Prisma.ReadNotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReadNotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadNotifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadNotifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReadNotifications
  **/
  _count?: true | ReadNotificationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReadNotificationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReadNotificationMaxAggregateInputType
}

export type GetReadNotificationAggregateType<T extends ReadNotificationAggregateArgs> = {
      [P in keyof T & keyof AggregateReadNotification]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReadNotification[P]>
    : Prisma.GetScalarType<T[P], AggregateReadNotification[P]>
}




export type ReadNotificationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReadNotificationWhereInput
  orderBy?: Prisma.ReadNotificationOrderByWithAggregationInput | Prisma.ReadNotificationOrderByWithAggregationInput[]
  by: Prisma.ReadNotificationScalarFieldEnum[] | Prisma.ReadNotificationScalarFieldEnum
  having?: Prisma.ReadNotificationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReadNotificationCountAggregateInputType | true
  _min?: ReadNotificationMinAggregateInputType
  _max?: ReadNotificationMaxAggregateInputType
}

export type ReadNotificationGroupByOutputType = {
  id: string
  readAt: Date
  _count: ReadNotificationCountAggregateOutputType | null
  _min: ReadNotificationMinAggregateOutputType | null
  _max: ReadNotificationMaxAggregateOutputType | null
}

export type GetReadNotificationGroupByPayload<T extends ReadNotificationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReadNotificationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReadNotificationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReadNotificationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReadNotificationGroupByOutputType[P]>
      }
    >
  >



export type ReadNotificationWhereInput = {
  AND?: Prisma.ReadNotificationWhereInput | Prisma.ReadNotificationWhereInput[]
  OR?: Prisma.ReadNotificationWhereInput[]
  NOT?: Prisma.ReadNotificationWhereInput | Prisma.ReadNotificationWhereInput[]
  id?: Prisma.StringFilter<"ReadNotification"> | string
  readAt?: Prisma.DateTimeFilter<"ReadNotification"> | Date | string
}

export type ReadNotificationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}

export type ReadNotificationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ReadNotificationWhereInput | Prisma.ReadNotificationWhereInput[]
  OR?: Prisma.ReadNotificationWhereInput[]
  NOT?: Prisma.ReadNotificationWhereInput | Prisma.ReadNotificationWhereInput[]
  readAt?: Prisma.DateTimeFilter<"ReadNotification"> | Date | string
}, "id">

export type ReadNotificationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
  _count?: Prisma.ReadNotificationCountOrderByAggregateInput
  _max?: Prisma.ReadNotificationMaxOrderByAggregateInput
  _min?: Prisma.ReadNotificationMinOrderByAggregateInput
}

export type ReadNotificationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReadNotificationScalarWhereWithAggregatesInput | Prisma.ReadNotificationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReadNotificationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReadNotificationScalarWhereWithAggregatesInput | Prisma.ReadNotificationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ReadNotification"> | string
  readAt?: Prisma.DateTimeWithAggregatesFilter<"ReadNotification"> | Date | string
}

export type ReadNotificationCreateInput = {
  id: string
  readAt?: Date | string
}

export type ReadNotificationUncheckedCreateInput = {
  id: string
  readAt?: Date | string
}

export type ReadNotificationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadNotificationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadNotificationCreateManyInput = {
  id: string
  readAt?: Date | string
}

export type ReadNotificationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadNotificationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReadNotificationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}

export type ReadNotificationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}

export type ReadNotificationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  readAt?: Prisma.SortOrder
}



export type ReadNotificationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  readAt?: boolean
}, ExtArgs["result"]["readNotification"]>

export type ReadNotificationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  readAt?: boolean
}, ExtArgs["result"]["readNotification"]>

export type ReadNotificationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  readAt?: boolean
}, ExtArgs["result"]["readNotification"]>

export type ReadNotificationSelectScalar = {
  id?: boolean
  readAt?: boolean
}

export type ReadNotificationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "readAt", ExtArgs["result"]["readNotification"]>

export type $ReadNotificationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReadNotification"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    readAt: Date
  }, ExtArgs["result"]["readNotification"]>
  composites: {}
}

export type ReadNotificationGetPayload<S extends boolean | null | undefined | ReadNotificationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload, S>

export type ReadNotificationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReadNotificationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReadNotificationCountAggregateInputType | true
  }

export interface ReadNotificationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReadNotification'], meta: { name: 'ReadNotification' } }
  /**
   * Find zero or one ReadNotification that matches the filter.
   * @param {ReadNotificationFindUniqueArgs} args - Arguments to find a ReadNotification
   * @example
   * // Get one ReadNotification
   * const readNotification = await prisma.readNotification.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReadNotificationFindUniqueArgs>(args: Prisma.SelectSubset<T, ReadNotificationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReadNotification that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReadNotificationFindUniqueOrThrowArgs} args - Arguments to find a ReadNotification
   * @example
   * // Get one ReadNotification
   * const readNotification = await prisma.readNotification.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReadNotificationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReadNotificationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReadNotification that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationFindFirstArgs} args - Arguments to find a ReadNotification
   * @example
   * // Get one ReadNotification
   * const readNotification = await prisma.readNotification.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReadNotificationFindFirstArgs>(args?: Prisma.SelectSubset<T, ReadNotificationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReadNotification that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationFindFirstOrThrowArgs} args - Arguments to find a ReadNotification
   * @example
   * // Get one ReadNotification
   * const readNotification = await prisma.readNotification.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReadNotificationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReadNotificationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReadNotifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReadNotifications
   * const readNotifications = await prisma.readNotification.findMany()
   * 
   * // Get first 10 ReadNotifications
   * const readNotifications = await prisma.readNotification.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const readNotificationWithIdOnly = await prisma.readNotification.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReadNotificationFindManyArgs>(args?: Prisma.SelectSubset<T, ReadNotificationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReadNotification.
   * @param {ReadNotificationCreateArgs} args - Arguments to create a ReadNotification.
   * @example
   * // Create one ReadNotification
   * const ReadNotification = await prisma.readNotification.create({
   *   data: {
   *     // ... data to create a ReadNotification
   *   }
   * })
   * 
   */
  create<T extends ReadNotificationCreateArgs>(args: Prisma.SelectSubset<T, ReadNotificationCreateArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReadNotifications.
   * @param {ReadNotificationCreateManyArgs} args - Arguments to create many ReadNotifications.
   * @example
   * // Create many ReadNotifications
   * const readNotification = await prisma.readNotification.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReadNotificationCreateManyArgs>(args?: Prisma.SelectSubset<T, ReadNotificationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReadNotifications and returns the data saved in the database.
   * @param {ReadNotificationCreateManyAndReturnArgs} args - Arguments to create many ReadNotifications.
   * @example
   * // Create many ReadNotifications
   * const readNotification = await prisma.readNotification.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReadNotifications and only return the `id`
   * const readNotificationWithIdOnly = await prisma.readNotification.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReadNotificationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReadNotificationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReadNotification.
   * @param {ReadNotificationDeleteArgs} args - Arguments to delete one ReadNotification.
   * @example
   * // Delete one ReadNotification
   * const ReadNotification = await prisma.readNotification.delete({
   *   where: {
   *     // ... filter to delete one ReadNotification
   *   }
   * })
   * 
   */
  delete<T extends ReadNotificationDeleteArgs>(args: Prisma.SelectSubset<T, ReadNotificationDeleteArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReadNotification.
   * @param {ReadNotificationUpdateArgs} args - Arguments to update one ReadNotification.
   * @example
   * // Update one ReadNotification
   * const readNotification = await prisma.readNotification.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReadNotificationUpdateArgs>(args: Prisma.SelectSubset<T, ReadNotificationUpdateArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReadNotifications.
   * @param {ReadNotificationDeleteManyArgs} args - Arguments to filter ReadNotifications to delete.
   * @example
   * // Delete a few ReadNotifications
   * const { count } = await prisma.readNotification.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReadNotificationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReadNotificationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReadNotifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReadNotifications
   * const readNotification = await prisma.readNotification.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReadNotificationUpdateManyArgs>(args: Prisma.SelectSubset<T, ReadNotificationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReadNotifications and returns the data updated in the database.
   * @param {ReadNotificationUpdateManyAndReturnArgs} args - Arguments to update many ReadNotifications.
   * @example
   * // Update many ReadNotifications
   * const readNotification = await prisma.readNotification.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReadNotifications and only return the `id`
   * const readNotificationWithIdOnly = await prisma.readNotification.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReadNotificationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReadNotificationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReadNotification.
   * @param {ReadNotificationUpsertArgs} args - Arguments to update or create a ReadNotification.
   * @example
   * // Update or create a ReadNotification
   * const readNotification = await prisma.readNotification.upsert({
   *   create: {
   *     // ... data to create a ReadNotification
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReadNotification we want to update
   *   }
   * })
   */
  upsert<T extends ReadNotificationUpsertArgs>(args: Prisma.SelectSubset<T, ReadNotificationUpsertArgs<ExtArgs>>): Prisma.Prisma__ReadNotificationClient<runtime.Types.Result.GetResult<Prisma.$ReadNotificationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReadNotifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationCountArgs} args - Arguments to filter ReadNotifications to count.
   * @example
   * // Count the number of ReadNotifications
   * const count = await prisma.readNotification.count({
   *   where: {
   *     // ... the filter for the ReadNotifications we want to count
   *   }
   * })
  **/
  count<T extends ReadNotificationCountArgs>(
    args?: Prisma.Subset<T, ReadNotificationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReadNotificationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReadNotification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReadNotificationAggregateArgs>(args: Prisma.Subset<T, ReadNotificationAggregateArgs>): Prisma.PrismaPromise<GetReadNotificationAggregateType<T>>

  /**
   * Group by ReadNotification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReadNotificationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReadNotificationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReadNotificationGroupByArgs['orderBy'] }
      : { orderBy?: ReadNotificationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReadNotificationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReadNotificationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReadNotification model
 */
readonly fields: ReadNotificationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReadNotification.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReadNotificationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReadNotification model
 */
export interface ReadNotificationFieldRefs {
  readonly id: Prisma.FieldRef<"ReadNotification", 'String'>
  readonly readAt: Prisma.FieldRef<"ReadNotification", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReadNotification findUnique
 */
export type ReadNotificationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * Filter, which ReadNotification to fetch.
   */
  where: Prisma.ReadNotificationWhereUniqueInput
}

/**
 * ReadNotification findUniqueOrThrow
 */
export type ReadNotificationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * Filter, which ReadNotification to fetch.
   */
  where: Prisma.ReadNotificationWhereUniqueInput
}

/**
 * ReadNotification findFirst
 */
export type ReadNotificationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * Filter, which ReadNotification to fetch.
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadNotifications to fetch.
   */
  orderBy?: Prisma.ReadNotificationOrderByWithRelationInput | Prisma.ReadNotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReadNotifications.
   */
  cursor?: Prisma.ReadNotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadNotifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadNotifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReadNotifications.
   */
  distinct?: Prisma.ReadNotificationScalarFieldEnum | Prisma.ReadNotificationScalarFieldEnum[]
}

/**
 * ReadNotification findFirstOrThrow
 */
export type ReadNotificationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * Filter, which ReadNotification to fetch.
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadNotifications to fetch.
   */
  orderBy?: Prisma.ReadNotificationOrderByWithRelationInput | Prisma.ReadNotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReadNotifications.
   */
  cursor?: Prisma.ReadNotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadNotifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadNotifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReadNotifications.
   */
  distinct?: Prisma.ReadNotificationScalarFieldEnum | Prisma.ReadNotificationScalarFieldEnum[]
}

/**
 * ReadNotification findMany
 */
export type ReadNotificationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * Filter, which ReadNotifications to fetch.
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReadNotifications to fetch.
   */
  orderBy?: Prisma.ReadNotificationOrderByWithRelationInput | Prisma.ReadNotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReadNotifications.
   */
  cursor?: Prisma.ReadNotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReadNotifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReadNotifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReadNotifications.
   */
  distinct?: Prisma.ReadNotificationScalarFieldEnum | Prisma.ReadNotificationScalarFieldEnum[]
}

/**
 * ReadNotification create
 */
export type ReadNotificationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * The data needed to create a ReadNotification.
   */
  data: Prisma.XOR<Prisma.ReadNotificationCreateInput, Prisma.ReadNotificationUncheckedCreateInput>
}

/**
 * ReadNotification createMany
 */
export type ReadNotificationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReadNotifications.
   */
  data: Prisma.ReadNotificationCreateManyInput | Prisma.ReadNotificationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReadNotification createManyAndReturn
 */
export type ReadNotificationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * The data used to create many ReadNotifications.
   */
  data: Prisma.ReadNotificationCreateManyInput | Prisma.ReadNotificationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReadNotification update
 */
export type ReadNotificationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * The data needed to update a ReadNotification.
   */
  data: Prisma.XOR<Prisma.ReadNotificationUpdateInput, Prisma.ReadNotificationUncheckedUpdateInput>
  /**
   * Choose, which ReadNotification to update.
   */
  where: Prisma.ReadNotificationWhereUniqueInput
}

/**
 * ReadNotification updateMany
 */
export type ReadNotificationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReadNotifications.
   */
  data: Prisma.XOR<Prisma.ReadNotificationUpdateManyMutationInput, Prisma.ReadNotificationUncheckedUpdateManyInput>
  /**
   * Filter which ReadNotifications to update
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * Limit how many ReadNotifications to update.
   */
  limit?: number
}

/**
 * ReadNotification updateManyAndReturn
 */
export type ReadNotificationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * The data used to update ReadNotifications.
   */
  data: Prisma.XOR<Prisma.ReadNotificationUpdateManyMutationInput, Prisma.ReadNotificationUncheckedUpdateManyInput>
  /**
   * Filter which ReadNotifications to update
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * Limit how many ReadNotifications to update.
   */
  limit?: number
}

/**
 * ReadNotification upsert
 */
export type ReadNotificationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * The filter to search for the ReadNotification to update in case it exists.
   */
  where: Prisma.ReadNotificationWhereUniqueInput
  /**
   * In case the ReadNotification found by the `where` argument doesn't exist, create a new ReadNotification with this data.
   */
  create: Prisma.XOR<Prisma.ReadNotificationCreateInput, Prisma.ReadNotificationUncheckedCreateInput>
  /**
   * In case the ReadNotification was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReadNotificationUpdateInput, Prisma.ReadNotificationUncheckedUpdateInput>
}

/**
 * ReadNotification delete
 */
export type ReadNotificationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
  /**
   * Filter which ReadNotification to delete.
   */
  where: Prisma.ReadNotificationWhereUniqueInput
}

/**
 * ReadNotification deleteMany
 */
export type ReadNotificationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReadNotifications to delete
   */
  where?: Prisma.ReadNotificationWhereInput
  /**
   * Limit how many ReadNotifications to delete.
   */
  limit?: number
}

/**
 * ReadNotification without action
 */
export type ReadNotificationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReadNotification
   */
  select?: Prisma.ReadNotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReadNotification
   */
  omit?: Prisma.ReadNotificationOmit<ExtArgs> | null
}
