
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  SuperAdmin: 'SuperAdmin',
  SuperAdminPasswordResetToken: 'SuperAdminPasswordResetToken',
  User: 'User',
  GymUser: 'GymUser',
  UserPasswordResetToken: 'UserPasswordResetToken',
  GlobalMember: 'GlobalMember',
  Plan: 'Plan',
  Gym: 'Gym',
  GymSubscription: 'GymSubscription',
  GymFeature: 'GymFeature',
  PlatformConfig: 'PlatformConfig',
  AuditLog: 'AuditLog',
  ReadNotification: 'ReadNotification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const SuperAdminScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  mobile: 'mobile',
  passwordHash: 'passwordHash',
  lastLogin: 'lastLogin',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SuperAdminScalarFieldEnum = (typeof SuperAdminScalarFieldEnum)[keyof typeof SuperAdminScalarFieldEnum]


export const SuperAdminPasswordResetTokenScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  superAdminId: 'superAdminId',
  used: 'used',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type SuperAdminPasswordResetTokenScalarFieldEnum = (typeof SuperAdminPasswordResetTokenScalarFieldEnum)[keyof typeof SuperAdminPasswordResetTokenScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  passwordHash: 'passwordHash',
  status: 'status',
  lastLogin: 'lastLogin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const GymUserScalarFieldEnum = {
  id: 'id',
  gymId: 'gymId',
  userId: 'userId',
  role: 'role',
  status: 'status',
  designation: 'designation',
  permissions: 'permissions',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GymUserScalarFieldEnum = (typeof GymUserScalarFieldEnum)[keyof typeof GymUserScalarFieldEnum]


export const UserPasswordResetTokenScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  userId: 'userId',
  used: 'used',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type UserPasswordResetTokenScalarFieldEnum = (typeof UserPasswordResetTokenScalarFieldEnum)[keyof typeof UserPasswordResetTokenScalarFieldEnum]


export const GlobalMemberScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  gender: 'gender',
  dob: 'dob',
  bloodGroup: 'bloodGroup',
  emergencyPhone: 'emergencyPhone',
  emergencyName: 'emergencyName',
  address: 'address',
  avatar: 'avatar',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GlobalMemberScalarFieldEnum = (typeof GlobalMemberScalarFieldEnum)[keyof typeof GlobalMemberScalarFieldEnum]


export const PlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  monthlyPrice: 'monthlyPrice',
  yearlyPrice: 'yearlyPrice',
  features: 'features',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlanScalarFieldEnum = (typeof PlanScalarFieldEnum)[keyof typeof PlanScalarFieldEnum]


export const GymScalarFieldEnum = {
  id: 'id',
  code: 'code',
  schemaName: 'schemaName',
  name: 'name',
  location: 'location',
  address: 'address',
  city: 'city',
  state: 'state',
  country: 'country',
  pincode: 'pincode',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  ownerName: 'ownerName',
  ownerPhone: 'ownerPhone',
  status: 'status',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GymScalarFieldEnum = (typeof GymScalarFieldEnum)[keyof typeof GymScalarFieldEnum]


export const GymSubscriptionScalarFieldEnum = {
  id: 'id',
  gymId: 'gymId',
  planId: 'planId',
  billingCycle: 'billingCycle',
  status: 'status',
  startDate: 'startDate',
  renewalDate: 'renewalDate',
  price: 'price',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GymSubscriptionScalarFieldEnum = (typeof GymSubscriptionScalarFieldEnum)[keyof typeof GymSubscriptionScalarFieldEnum]


export const GymFeatureScalarFieldEnum = {
  gymId: 'gymId',
  featureKey: 'featureKey',
  enabled: 'enabled',
  updatedByAdminId: 'updatedByAdminId',
  updatedAt: 'updatedAt'
} as const

export type GymFeatureScalarFieldEnum = (typeof GymFeatureScalarFieldEnum)[keyof typeof GymFeatureScalarFieldEnum]


export const PlatformConfigScalarFieldEnum = {
  key: 'key',
  platformName: 'platformName',
  currency: 'currency',
  defaultTimezone: 'defaultTimezone',
  supportEmail: 'supportEmail',
  supportPhone: 'supportPhone',
  maintenanceMode: 'maintenanceMode',
  maintenanceMessage: 'maintenanceMessage',
  updatedAt: 'updatedAt'
} as const

export type PlatformConfigScalarFieldEnum = (typeof PlatformConfigScalarFieldEnum)[keyof typeof PlatformConfigScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  type: 'type',
  action: 'action',
  details: 'details',
  metadata: 'metadata',
  entityType: 'entityType',
  entityId: 'entityId',
  gymId: 'gymId',
  actorAdminId: 'actorAdminId',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const ReadNotificationScalarFieldEnum = {
  id: 'id',
  readAt: 'readAt'
} as const

export type ReadNotificationScalarFieldEnum = (typeof ReadNotificationScalarFieldEnum)[keyof typeof ReadNotificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

