
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model SuperAdmin
 * 
 */
export type SuperAdmin = Prisma.SuperAdminModel
/**
 * Model SuperAdminPasswordResetToken
 * 
 */
export type SuperAdminPasswordResetToken = Prisma.SuperAdminPasswordResetTokenModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model GymUser
 * 
 */
export type GymUser = Prisma.GymUserModel
/**
 * Model UserPasswordResetToken
 * 
 */
export type UserPasswordResetToken = Prisma.UserPasswordResetTokenModel
/**
 * Model GlobalMember
 * 
 */
export type GlobalMember = Prisma.GlobalMemberModel
/**
 * Model Plan
 * 
 */
export type Plan = Prisma.PlanModel
/**
 * Model Gym
 * 
 */
export type Gym = Prisma.GymModel
/**
 * Model GymSubscription
 * 
 */
export type GymSubscription = Prisma.GymSubscriptionModel
/**
 * Model GymFeature
 * 
 */
export type GymFeature = Prisma.GymFeatureModel
/**
 * Model PlatformConfig
 * 
 */
export type PlatformConfig = Prisma.PlatformConfigModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model ReadNotification
 * 
 */
export type ReadNotification = Prisma.ReadNotificationModel
