
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const GymRole = {
  GYM_ADMIN: 'GYM_ADMIN',
  RECEPTIONIST: 'RECEPTIONIST',
  TRAINER: 'TRAINER'
} as const

export type GymRole = (typeof GymRole)[keyof typeof GymRole]


export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const GymStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  TRIAL: 'TRIAL'
} as const

export type GymStatus = (typeof GymStatus)[keyof typeof GymStatus]


export const BillingCycle = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
} as const

export type BillingCycle = (typeof BillingCycle)[keyof typeof BillingCycle]


export const GymSubscriptionStatus = {
  ACTIVE: 'ACTIVE',
  TRIAL: 'TRIAL',
  PAST_DUE: 'PAST_DUE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
} as const

export type GymSubscriptionStatus = (typeof GymSubscriptionStatus)[keyof typeof GymSubscriptionStatus]


export const ActivityType = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  STATUS: 'STATUS',
  SUBSCRIPTION: 'SUBSCRIPTION',
  SETTINGS: 'SETTINGS'
} as const

export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType]
