import type { ThemeConfig } from 'antd';

export const gymentTheme: ThemeConfig = {
  token: {
    colorPrimary: '#2FAE68',
    colorSuccess: '#2FAE68',
    colorWarning: '#B8791C',
    colorError: '#C5432E',
    colorInfo: '#3B6FB0',
    colorTextBase: '#16211B',
    colorText: '#16211B',
    colorTextHeading: '#16211B',
    colorTextSecondary: '#4A5550',
    colorTextPlaceholder: '#5A6660',
    colorBgBase: '#FFFFFF',
    colorBorder: '#CED5D1',
    colorLink: '#22935A',
    borderRadius: 10,
    fontFamily: 'var(--font-plus-jakarta), Plus Jakarta Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  components: {
    Table: {
      headerBg: '#FFFFFF',
      headerColor: '#4A5550',
      borderColor: '#E3E8E5',
      cellPaddingBlock: 11,
      cellPaddingInline: 12,
      fontSize: 13,
      rowHoverBg: '#F6F9F7',
    },
    Button: {
      borderRadius: 9,
      colorPrimary: '#2FAE68',
      colorPrimaryHover: '#22935A',
      colorPrimaryActive: '#1c7849',
      colorText: '#16211B',
      borderColorDisabled: '#E3E8E5',
      defaultBorderColor: '#CED5D1',
      defaultBg: '#FFFFFF',
      defaultHoverBg: '#F6F9F7',
      defaultHoverBorderColor: '#2FAE68',
      defaultHoverColor: '#16211B',
    },
    Input: {
      borderRadius: 8,
      colorBorder: '#CED5D1',
      hoverBorderColor: '#2FAE68',
      activeBorderColor: '#2FAE68',
      colorBgContainer: '#FFFFFF',
      colorText: '#16211B',
      colorTextPlaceholder: '#5A6660',
    },
    Select: {
      borderRadius: 8,
      colorBorder: '#CED5D1',
      hoverBorderColor: '#2FAE68',
      activeBorderColor: '#2FAE68',
      colorBgContainer: '#FFFFFF',
      colorText: '#16211B',
      colorTextPlaceholder: '#5A6660',
    },
    DatePicker: {
      borderRadius: 8,
      colorBorder: '#CED5D1',
      hoverBorderColor: '#2FAE68',
      activeBorderColor: '#2FAE68',
      colorBgContainer: '#FFFFFF',
      colorText: '#16211B',
      colorTextPlaceholder: '#5A6660',
    },
    Modal: {
      borderRadiusLG: 14,
      headerBg: '#FFFFFF',
      contentBg: '#FFFFFF',
      titleColor: '#16211B',
      titleFontSize: 16,
    },
    Drawer: {
      colorBgElevated: '#FFFFFF',
    },
    Tabs: {
      colorPrimary: '#2FAE68',
      itemColor: '#4A5550',
      itemHoverColor: '#16211B',
      itemSelectedColor: '#16211B',
      inkBarColor: '#2FAE68',
    },
    Tag: {
      borderRadiusSM: 99,
    },
    Badge: {
      colorError: '#C5432E',
    },
    Pagination: {
      borderRadius: 8,
      colorPrimary: '#2FAE68',
    },
  },
};
